using System.ComponentModel.DataAnnotations;
namespace StbMonitoring.Application.Contracts;

public sealed record LoginRequest([Required] string UsernameOrEmail, [Required] string Password);
public sealed record LoginResponse(string Token, DateTime ExpiresAt, UserResponse User);
public sealed record RefreshRequest(string Token);
public sealed record CreateUserRequest([Required,MinLength(3)] string Username, [Required,EmailAddress] string Email, [Required,MinLength(8)] string Password, [Required] string FirstName, [Required] string LastName, [Required,MinLength(1)] IReadOnlyCollection<string>? Roles);
public sealed record UpdateUserRequest([Required,EmailAddress] string Email, [Required] string FirstName, [Required] string LastName);
public sealed record UpdateProfileRequest([Required,EmailAddress] string Email, [Required] string FirstName, [Required] string LastName);
public sealed record ChangePasswordRequest([Required] string CurrentPassword, [Required,MinLength(8)] string NewPassword);
public sealed record AssignRoleRequest([Required] string RoleName);
public sealed record UserResponse(Guid Id, string Username, string Email, string FirstName, string LastName, bool IsActive, DateTime CreatedAt, DateTime? LastLoginAt, IReadOnlyCollection<string> Roles, IReadOnlyCollection<string> Permissions);
public sealed record RoleResponse(Guid Id, string Name, string Description, bool IsActive, IReadOnlyCollection<string> Permissions);
public sealed record CreateRoleRequest([Required,RegularExpression("^[A-Za-z][A-Za-z0-9_]{2,59}$")] string Name, string Description);
public sealed record UpdateRoleRequest([Required,RegularExpression("^[A-Za-z][A-Za-z0-9_]{2,59}$")] string Name, string Description);
public sealed record SetRolePermissionsRequest(IReadOnlyCollection<string> Permissions);
public sealed record PermissionResponse(Guid Id, string Name, string Description);
public sealed record CreatePermissionRequest([Required,RegularExpression("^[a-z][a-z0-9_.]{2,99}$")] string Name, string Description);
public sealed record UpdatePermissionRequest([Required,RegularExpression("^[a-z][a-z0-9_.]{2,99}$")] string Name, string Description);
public sealed record AuditLogResponse(Guid Id, Guid? UserId, string Action, string EntityName, Guid? EntityId, string? Detail, string? IpAddress, DateTime CreatedAt, bool Success);
public sealed record AuthenticatedUser(Guid Id, string Username, string Email, IReadOnlyCollection<string> Roles, IReadOnlyCollection<string> Permissions);
public sealed record TokenResult(string Token, DateTime ExpiresAt);
