using System.ComponentModel.DataAnnotations;using StbMonitoring.Domain.Entities;
namespace StbMonitoring.Application.Contracts;
public sealed record AlertRuleRequest([Required]string Name,string Description,AlertEventType EventType,AlertSeverity Severity,[Range(1,100)]int ConsecutiveFailures,[Range(1,1440)]int DeduplicationMinutes,bool AutoResolve,bool NotifyInApp,Guid? SystemId,Guid? EndpointId);
public sealed record AlertRuleResponse(Guid Id,string Name,string Description,AlertEventType EventType,AlertSeverity Severity,int ConsecutiveFailures,int DeduplicationMinutes,bool AutoResolve,bool NotifyInApp,bool IsActive,Guid? SystemId,Guid? EndpointId);
public sealed record AlertResponse(Guid Id,string AlertNumber,Guid SystemId,string SystemName,Guid EndpointId,string EndpointName,AlertEventType Type,string Title,string Description,AlertSeverity Severity,AlertStatus Status,int OccurrenceCount,DateTime FirstDetectedAt,DateTime LastDetectedAt,DateTime? AcknowledgedAt,DateTime? ResolvedAt,Guid? IncidentId,string? LastError);
public sealed record AlertDetailResponse(AlertResponse Alert,IReadOnlyCollection<AlertOccurrenceResponse> Occurrences);
public sealed record AlertOccurrenceResponse(Guid Id,Guid CheckResultId,MonitoringStatus Status,string? ErrorType,string? ErrorMessage,DateTime DetectedAt);
public sealed record CreateIncidentRequest(Guid? AlertId,Guid? SystemId,Guid? EndpointId,[Required]string Title,[Required]string Description,IncidentCategory Category,IncidentPriority Priority);
public sealed record UpdateIncidentRequest(Guid? SystemId,Guid? EndpointId,[Required]string Title,[Required]string Description,IncidentCategory Category,IncidentPriority Priority);
public sealed record AssignIncidentRequest(Guid UserId);
public sealed record ResolveIncidentRequest([Required]string Summary,string? RootCause,[Required]string CorrectiveAction,string? PreventiveAction,string? ResolutionEvidence);
public sealed record AddCommentRequest([Required]string Content,string CommentType="Comment",bool IsInternal=true);
public sealed record IncidentActionReasonRequest([Required]string Reason);
public sealed record IncidentResponse(Guid Id,string IncidentNumber,Guid? AlertId,Guid? SystemId,Guid? EndpointId,string? SystemName,string Title,string Description,IncidentCategory Category,IncidentPriority Priority,IncidentStatus Status,SlaStatus SlaStatus,Guid? AssignedToUserId,string? AssignedToName,DateTime? ResponseDueAt,DateTime? ResolutionDueAt,DateTime? ResolvedAt,string? ResolutionSummary,string? RootCause,string? CorrectiveAction,string? PreventiveAction,string? ResolutionEvidence,string? CancellationReason,DateTime? CancelledAt,bool IsArchived,DateTime? ArchivedAt,Guid? ArchivedByUserId,int ReopenCount,DateTime CreatedAt,DateTime UpdatedAt);
public sealed record IncidentDetailResponse(IncidentResponse Incident,IReadOnlyCollection<CommentResponse> Comments,IReadOnlyCollection<HistoryResponse> History);
public sealed record CommentResponse(Guid Id,Guid UserId,string UserName,string Content,string CommentType,bool IsInternal,DateTime CreatedAt);
public sealed record HistoryResponse(Guid Id,Guid? UserId,string Action,string? OldValue,string? NewValue,string? Details,DateTime CreatedAt);
public sealed record SlaPolicyRequest([Required]string Name,string Description,IncidentPriority Priority,[Range(1,100000)]int ResponseTimeMinutes,[Range(1,100000)]int ResolutionTimeMinutes,[Range(1,90)]int WarningPercentage);
public sealed record SlaPolicyResponse(Guid Id,string Name,string Description,IncidentPriority Priority,int ResponseTimeMinutes,int ResolutionTimeMinutes,int WarningPercentage,bool IsActive);
public sealed record NotificationResponse(Guid Id,string Type,string Title,string Message,AlertSeverity Severity,string? EntityType,Guid? EntityId,string? ActionUrl,bool IsRead,DateTime CreatedAt);
public sealed record OperationsSummary(int OpenAlerts,int CriticalAlerts,int OpenIncidents,int UnassignedIncidents,int SlaBreached,int UnreadNotifications);
