// API de consultation paginée et cycle acquittement-résolution-clôture des alertes.
using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using StbMonitoring.Application.Contracts;using StbMonitoring.Application.Interfaces;using StbMonitoring.Domain.Constants;using StbMonitoring.Domain.Entities;using StbMonitoring.Infrastructure.Persistence;
namespace StbMonitoring.Api.Controllers;
[ApiController,Route("api/alerts"),Authorize]public sealed class AlertsController(IOperationsService service,IIdentityStore identity,MonitoringDbContext db):ControllerBase
{
 [HttpGet,Authorize(Policy=PermissionNames.AlertsRead)]public async Task<IActionResult>All(CancellationToken ct)=>Ok(await service.AlertsAsync(ct));
 [HttpGet("paged"),Authorize(Policy=PermissionNames.AlertsRead)]public async Task<IActionResult>Paged([FromQuery]int page=1,[FromQuery]int pageSize=12,[FromQuery]string? search=null,[FromQuery]AlertSeverity? severity=null,[FromQuery]AlertStatus? status=null,[FromQuery]string view="action",CancellationToken ct=default){page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,6,50);var q=db.Alerts.AsNoTracking();q=view.ToLowerInvariant() switch{"history"=>q.Where(x=>x.Status==AlertStatus.Resolved||x.Status==AlertStatus.Closed),"incident"=>q.Where(x=>x.IncidentId!=null&&(x.Status==AlertStatus.Open||x.Status==AlertStatus.Acknowledged)),_=>q.Where(x=>(x.Status==AlertStatus.Open||x.Status==AlertStatus.Acknowledged)&&(x.IncidentId==null||db.Incidents.Any(i=>i.Id==x.IncidentId&&i.Status!=IncidentStatus.Resolved&&i.Status!=IncidentStatus.Closed&&i.Status!=IncidentStatus.Cancelled)))};if(!string.IsNullOrWhiteSpace(search)){var s=search.Trim().ToLower();q=q.Where(x=>x.AlertNumber.ToLower().Contains(s)||x.Title.ToLower().Contains(s));}if(severity.HasValue)q=q.Where(x=>x.Severity==severity);if(status.HasValue)q=q.Where(x=>x.Status==status);var total=await q.CountAsync(ct);var today=DateTime.UtcNow.Date;var todayTotal=await db.Alerts.CountAsync(x=>x.CreatedAt>=today,ct);var ids=await q.OrderByDescending(x=>x.LastDetectedAt).Skip((page-1)*pageSize).Take(pageSize).Select(x=>x.Id).ToArrayAsync(ct);var all=await service.AlertsAsync(ct);var items=ids.Select(id=>all.Single(x=>x.Id==id)).ToArray();return Ok(new{items,total,todayTotal,page,pageSize,totalPages=(int)Math.Ceiling(total/(double)pageSize)});}
 [HttpGet("{id:guid}"),Authorize(Policy=PermissionNames.AlertsRead)]public async Task<IActionResult>One(Guid id,CancellationToken ct){var x=await service.AlertAsync(id,ct);return x is null?NotFound():Ok(x);}
 [HttpPost("{id:guid}/acknowledge"),Authorize(Policy=PermissionNames.AlertsAcknowledge)]public async Task<IActionResult>Acknowledge(Guid id,CancellationToken ct){await service.AcknowledgeAsync(id,Actor(),ct);await Audit("ALERT_ACKNOWLEDGED",id,ct);return NoContent();}
 [HttpPost("{id:guid}/resolve"),Authorize(Policy=PermissionNames.AlertsAcknowledge)]public async Task<IActionResult>Resolve(Guid id,CancellationToken ct){await service.ResolveAlertAsync(id,ct);await Audit("ALERT_RESOLVED",id,ct);return NoContent();}
 [HttpPost("{id:guid}/close"),Authorize(Policy=PermissionNames.AlertsAcknowledge)]public async Task<IActionResult>Close(Guid id,CancellationToken ct){await service.CloseAlertAsync(id,Actor(),ct);await Audit("ALERT_CLOSED",id,ct);return NoContent();}
 [HttpPost("{id:guid}/incident"),Authorize(Policy=PermissionNames.IncidentsManage)]public async Task<IActionResult>CreateIncident(Guid id,CancellationToken ct){var detail=await service.AlertAsync(id,ct);if(detail is null)return NotFound();if(detail.Alert.IncidentId.HasValue)return Conflict(new{message="Cette alerte possède déjà un incident."});var a=detail.Alert;var category=a.Type.ToString().StartsWith("Tls",StringComparison.OrdinalIgnoreCase)?IncidentCategory.Certificate:IncidentCategory.Availability;var priority=a.Severity==AlertSeverity.Critical?IncidentPriority.P1Critical:a.Severity==AlertSeverity.Major?IncidentPriority.P2High:IncidentPriority.P3Medium;return Ok(await service.CreateIncidentAsync(new CreateIncidentRequest(a.Id,a.SystemId,a.EndpointId,a.Title,a.Description,category,priority),Actor(),ct));}
 private Guid Actor()=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);private async Task Audit(string action,Guid id,CancellationToken ct){identity.AddAudit(new(Actor(),action,"Alert",id,null,HttpContext.Connection.RemoteIpAddress?.ToString()));await identity.SaveChangesAsync(ct);}
}
