// API du catalogue SI, des endpoints, contrôles manuels et preuves techniques.
using System.Security.Claims;using System.Text;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using StbMonitoring.Application.Contracts;using StbMonitoring.Application.Interfaces;using StbMonitoring.Domain.Constants;using StbMonitoring.Domain.Entities;using StbMonitoring.Infrastructure.Persistence;
namespace StbMonitoring.Api.Controllers;
[ApiController,Route("api/systems"),Authorize]
public sealed class SystemsController(IMonitoringService monitoring,IIdentityStore identity,MonitoringDbContext db):ControllerBase
{
 [HttpGet,Authorize(Policy=PermissionNames.SystemsRead)]public async Task<IActionResult>All([FromQuery]bool includeArchived,CancellationToken ct)=>Ok(await monitoring.GetSystemsAsync(includeArchived,ct));
 [HttpGet("{id:guid}"),Authorize(Policy=PermissionNames.SystemsRead)]public async Task<IActionResult>One(Guid id,CancellationToken ct){var x=await monitoring.GetSystemAsync(id,ct);return x is null?NotFound():Ok(x);}
 [HttpPost,Authorize(Policy=PermissionNames.SystemsManage)]public async Task<IActionResult>Create(CreateSystemRequest r,CancellationToken ct){var x=await monitoring.CreateSystemAsync(r,ct);await Audit("SYSTEM_CREATED",x.Id,ct);return CreatedAtAction(nameof(One),new{id=x.Id},x);}
 [HttpPut("{id:guid}"),Authorize(Policy=PermissionNames.SystemsManage)]public async Task<IActionResult>Update(Guid id,UpdateSystemRequest r,CancellationToken ct){var x=await monitoring.UpdateSystemAsync(id,r,ct);await Audit("SYSTEM_UPDATED",id,ct);return Ok(x);}
 [HttpPatch("{id:guid}/monitoring"),Authorize(Policy=PermissionNames.SystemsManage)]public async Task<IActionResult>Monitoring(Guid id,[FromQuery]bool enabled,CancellationToken ct){await monitoring.SetMonitoringAsync(id,enabled,ct);await Audit(enabled?"SYSTEM_ENABLED":"SYSTEM_DISABLED",id,ct);return NoContent();}
 [HttpPatch("{id:guid}/archived"),Authorize(Policy=PermissionNames.SystemsManage)]public async Task<IActionResult>Archived(Guid id,[FromQuery]bool value,CancellationToken ct){await monitoring.SetArchivedAsync(id,value,ct);await Audit(value?"SYSTEM_ARCHIVED":"SYSTEM_RESTORED",id,ct);return NoContent();}
 [HttpDelete("{id:guid}"),Authorize(Policy=PermissionNames.SystemsManage)]public async Task<IActionResult>Delete(Guid id,CancellationToken ct){await monitoring.DeleteSystemAsync(id,ct);await Audit("SYSTEM_DELETED",id,ct);return NoContent();}
 [HttpPost("{id:guid}/endpoints"),Authorize(Policy=PermissionNames.SystemsManage)]public async Task<IActionResult>CreateEndpoint(Guid id,UpsertEndpointRequest r,CancellationToken ct){var x=await monitoring.CreateEndpointAsync(id,r,ct);await Audit("ENDPOINT_CREATED",x.Id,ct);return Created($"/api/systems/{id}/endpoints/{x.Id}",x);}
 [HttpPut("endpoints/{id:guid}"),Authorize(Policy=PermissionNames.SystemsManage)]public async Task<IActionResult>UpdateEndpoint(Guid id,UpsertEndpointRequest r,CancellationToken ct){var x=await monitoring.UpdateEndpointAsync(id,r,ct);await Audit("ENDPOINT_UPDATED",id,ct);return Ok(x);}
 [HttpPatch("endpoints/{id:guid}/active"),Authorize(Policy=PermissionNames.SystemsManage)]public async Task<IActionResult>EndpointActive(Guid id,[FromQuery]bool value,CancellationToken ct){await monitoring.SetEndpointActiveAsync(id,value,ct);await Audit(value?"ENDPOINT_ENABLED":"ENDPOINT_DISABLED",id,ct);return NoContent();}
 [HttpDelete("endpoints/{id:guid}"),Authorize(Policy=PermissionNames.SystemsManage)]public async Task<IActionResult>DeleteEndpoint(Guid id,CancellationToken ct){await monitoring.DeleteEndpointAsync(id,ct);await Audit("ENDPOINT_DELETED",id,ct);return NoContent();}
 [HttpPost("endpoints/{id:guid}/execute"),Authorize(Policy=PermissionNames.ChecksExecute)]public async Task<IActionResult>Execute(Guid id,CancellationToken ct){var x=await monitoring.ExecuteEndpointAsync(id,true,Actor(),ct);await Audit("CHECK_TRIGGERED_MANUALLY",id,ct);return Ok(x);}
 [HttpGet("checks"),Authorize(Policy=PermissionNames.ChecksRead)]public async Task<IActionResult>Results([FromQuery]Guid? systemId,[FromQuery]Guid? endpointId,[FromQuery]MonitoringStatus? status,[FromQuery]DateTime? from,[FromQuery]DateTime? to,CancellationToken ct,[FromQuery]int take=100)=>Ok(await monitoring.GetResultsAsync(systemId,endpointId,status,from,to,take,ct));
 [HttpGet("checks/{id:guid}/evidence"),Authorize(Policy=PermissionNames.ChecksRead)]public async Task<IActionResult>Evidence(Guid id,CancellationToken ct){var x=await db.CheckResults.AsNoTracking().Include(r=>r.Endpoint).Include(r=>r.System).SingleOrDefaultAsync(r=>r.Id==id,ct);if(x is null)return NotFound();var json=System.Text.Json.JsonSerializer.Serialize(new{x.Id,system=x.System.Name,endpoint=x.Endpoint.Name,x.Status,x.Success,x.StartedAt,x.CompletedAt,x.DurationMs,x.HttpStatusCode,x.ErrorType,x.ErrorMessage,x.TriggeredManually,x.Metadata},new System.Text.Json.JsonSerializerOptions{WriteIndented=true});return File(Encoding.UTF8.GetBytes(json),"application/json",$"preuve-controle-{x.Id}.json");}
 private Guid Actor()=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);private async Task Audit(string action,Guid entityId,CancellationToken ct){identity.AddAudit(new AuditLog(Actor(),action,action.StartsWith("SYSTEM")?"System":"MonitoringEndpoint",entityId,null,HttpContext.Connection.RemoteIpAddress?.ToString()));await identity.SaveChangesAsync(ct);}
}
