using Microsoft.EntityFrameworkCore;using StbMonitoring.Application.Interfaces;using StbMonitoring.Domain.Constants;using StbMonitoring.Domain.Entities;using StbMonitoring.Infrastructure.Persistence;
namespace StbMonitoring.Api.Workers;
/// <summary>
/// Reprend les escalades persistées même après un redémarrage de l'API.
/// Niveau 0 : superviseur ; niveau 1 : manager IT. Une résolution, clôture ou
/// annulation arrête immédiatement la chaîne de notifications.
/// </summary>
public sealed class IncidentEscalationWorker(IServiceScopeFactory scopes,ILogger<IncidentEscalationWorker> logger):BackgroundService
{
 protected override async Task ExecuteAsync(CancellationToken ct){await Task.Delay(TimeSpan.FromSeconds(15),ct);while(!ct.IsCancellationRequested){try{using var scope=scopes.CreateScope();var db=scope.ServiceProvider.GetRequiredService<MonitoringDbContext>();var channel=scope.ServiceProvider.GetRequiredService<INotificationChannel>();var due=await db.IncidentEscalations.Where(x=>x.CompletedAt==null&&x.NextEscalationAt<=DateTime.UtcNow).ToArrayAsync(ct);foreach(var x in due){var incident=await db.Incidents.FindAsync([x.IncidentId],ct);if(incident is null||incident.Status is IncidentStatus.Resolved or IncidentStatus.Closed or IncidentStatus.Cancelled){x.Complete("Incident terminé");continue;}var role=x.Level==0?RoleNames.Supervisor:RoleNames.ManagerIt;var users=await db.Users.Where(u=>u.IsActive&&u.Role==role).ToArrayAsync(ct);foreach(var u in users){var p=await db.UserNotificationPreferences.FindAsync([u.Id],ct);var subject=$"[ESCALADE {role}] {incident.IncidentNumber} — {incident.Title}";if(p?.EmailEnabled!=false)await channel.SendEmailAsync(u.Email,subject,$"<h2>{subject}</h2><p>Incident critique non résolu.</p>",ct);if(p?.SmsEnabled==true&&!string.IsNullOrWhiteSpace(p.PhoneNumber))await channel.SendSmsAsync(p.PhoneNumber,subject,ct);}var delay=users.Select(u=>db.UserNotificationPreferences.Local.FirstOrDefault(p=>p.UserId==u.Id)?.EscalationDelayMinutes??15).DefaultIfEmpty(15).Min();x.Advance($"Notifié: {role}",delay);}await db.SaveChangesAsync(ct);}catch(OperationCanceledException)when(ct.IsCancellationRequested){break;}catch(Exception ex){logger.LogError(ex,"Erreur du worker d'escalade.");}await Task.Delay(TimeSpan.FromSeconds(30),ct);}}
}
