namespace StbMonitoring.Domain.Entities;
public sealed class MonitoringEndpoint
{
    private MonitoringEndpoint() { }
    public MonitoringEndpoint(Guid systemId,string name,string url,CheckType checkType,string httpMethod,int expectedStatusCode,int timeoutSeconds,int intervalSeconds,int degradedThresholdMs,int downThresholdMs,bool isCritical,string? expectedJsonProperty,string? expectedJsonValue)
    {Id=Guid.NewGuid();SystemId=systemId;Update(name,url,checkType,httpMethod,expectedStatusCode,timeoutSeconds,intervalSeconds,degradedThresholdMs,downThresholdMs,isCritical,expectedJsonProperty,expectedJsonValue);NextCheckAt=DateTime.UtcNow;}
    public Guid Id{get;private set;} public Guid SystemId{get;private set;} public MonitoredSystem System{get;private set;}=null!; public string Name{get;private set;}=string.Empty; public string Url{get;private set;}=string.Empty; public CheckType CheckType{get;private set;} public string HttpMethod{get;private set;}="GET";
    public int ExpectedStatusCode{get;private set;}=200; public int TimeoutSeconds{get;private set;}=10; public int IntervalSeconds{get;private set;}=60; public int DegradedThresholdMs{get;private set;}=1500; public int DownThresholdMs{get;private set;}=3000; public bool IsCritical{get;private set;}=true; public bool IsActive{get;private set;}=true;
    public string? ExpectedJsonProperty{get;private set;} public string? ExpectedJsonValue{get;private set;} public MonitoringStatus Status{get;private set;}=MonitoringStatus.Unknown; public DateTime? LastCheckedAt{get;private set;} public DateTime NextCheckAt{get;private set;} public long? LastDurationMs{get;private set;} public string? LastError{get;private set;} public ICollection<CheckResult> Results{get;}=new List<CheckResult>();
    public void Update(string name,string url,CheckType checkType,string httpMethod,int expectedStatusCode,int timeoutSeconds,int intervalSeconds,int degradedThresholdMs,int downThresholdMs,bool isCritical,string? expectedJsonProperty,string? expectedJsonValue){if(string.IsNullOrWhiteSpace(name))throw new ArgumentException("Le nom de l'endpoint est obligatoire.");if(!Uri.TryCreate(url,UriKind.Absolute,out var uri)||uri.Scheme is not("http"or"https"))throw new ArgumentException("URL HTTP/HTTPS invalide.");var method=httpMethod.Trim().ToUpperInvariant();if(method is not("GET"or"HEAD"or"POST"))throw new ArgumentException("Méthode HTTP non supportée.");if(expectedStatusCode is <100 or >599)throw new ArgumentOutOfRangeException(nameof(expectedStatusCode));if(timeoutSeconds is <1 or >300)throw new ArgumentOutOfRangeException(nameof(timeoutSeconds));if(intervalSeconds is <10 or >86400)throw new ArgumentOutOfRangeException(nameof(intervalSeconds));if(degradedThresholdMs<1||downThresholdMs<degradedThresholdMs)throw new ArgumentException("Les seuils de performance sont invalides.");Name=name.Trim();Url=url.Trim();CheckType=checkType;HttpMethod=method;ExpectedStatusCode=expectedStatusCode;TimeoutSeconds=timeoutSeconds;IntervalSeconds=intervalSeconds;DegradedThresholdMs=degradedThresholdMs;DownThresholdMs=downThresholdMs;IsCritical=isCritical;ExpectedJsonProperty=expectedJsonProperty?.Trim();ExpectedJsonValue=expectedJsonValue?.Trim();}
    public void SetActive(bool active){IsActive=active;if(!active)Status=MonitoringStatus.Unknown;NextCheckAt=DateTime.UtcNow;}
    public void Record(MonitoringStatus status,long durationMs,string? error){Status=status;LastDurationMs=durationMs;LastError=error;LastCheckedAt=DateTime.UtcNow;NextCheckAt=DateTime.UtcNow.AddSeconds(IntervalSeconds);}
}
