/** Génération locale des rapports : le backend fournit uniquement les données JSON. */
import{Injectable}from'@angular/core';
import{firstValueFrom,forkJoin}from'rxjs';
import{jsPDF}from'jspdf';
import autoTable from'jspdf-autotable';
import*as ExcelJS from'exceljs';
import{OperationsService,ReportData,ReportIncident,ReportingDashboard}from'./operations.service';

type Period='custom'|'monthly'|'annual';

@Injectable({providedIn:'root'})
export class ReportExportService{
 private readonly navy=[18,59,93]as const;private readonly teal=[8,126,139]as const;private readonly muted=[97,114,126]as const;
 constructor(private api:OperationsService){}

 async export(format:'pdf'|'xlsx',period:Period,from:string,to:string):Promise<Blob>{const range=this.range(period,from,to);const result=await firstValueFrom(forkJoin({dashboard:this.api.reporting(range.from,range.to),details:this.api.reportData(range.from,range.to)}));return format==='pdf'?await this.pdf(result.dashboard,result.details,period):await this.xlsx(result.dashboard,result.details,period)}

 private async pdf(k:ReportingDashboard,data:ReportData,period:Period){
  const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});const logo=await this.logo();const incidents=data.incidents;
  doc.setFillColor(245,248,250);doc.rect(0,0,210,297,'F');
  doc.setTextColor(...this.navy);doc.setFont('helvetica','bold');doc.setFontSize(20);doc.text(this.title(period),12,40);
  doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(...this.muted);doc.text(`Période du ${this.date(data.from)} au ${this.date(data.to)} - généré le ${this.dateTime(data.generatedAt)}`,12,47);
  this.kpis(doc,k,incidents.length);this.charts(doc,k);
  autoTable(doc,{startY:139,margin:{top:31,bottom:18,left:10,right:10},head:[['Numéro','Titre / système','Priorité','Statut','SLA','Technicien','Création']],body:incidents.map(i=>[i.incidentNumber,`${i.title}\n${i.systemName}`,this.priority(i.priority),this.status(i.status),this.sla(i.slaStatus),i.technician,this.dateTime(i.createdAt)]),theme:'grid',styles:{font:'helvetica',fontSize:7,cellPadding:2.2,textColor:[24,37,46],lineColor:[222,232,237],lineWidth:.2,overflow:'linebreak'},headStyles:{fillColor:[18,59,93],textColor:[255,255,255],fontStyle:'bold',fontSize:7.2},alternateRowStyles:{fillColor:[240,245,247]},columnStyles:{0:{cellWidth:23,fontStyle:'bold',textColor:[18,59,93]},1:{cellWidth:48},2:{cellWidth:18},3:{cellWidth:18},4:{cellWidth:18},5:{cellWidth:28},6:{cellWidth:26}}});
  this.resolutions(doc,incidents);const pages=doc.getNumberOfPages();for(let page=1;page<=pages;page++){doc.setPage(page);this.header(doc,logo,data);this.footer(doc,page,pages)}
  return doc.output('blob');
 }

 private kpis(doc:jsPDF,k:ReportingDashboard,total:number){const values=[['Disponibilité',`${k.kpis.availability}%`,'Contrôles UP'],['Alertes',String(k.kpis.openAlerts),'Actives'],['Incidents',String(total),'Sur la période'],['SLA respecté',`${k.kpis.slaComplianceRate}%`,'Incidents mesurés'],['MTTD',this.duration(k.kpis.meanDetectionMinutes),'Détection'],['MTTA',this.duration(k.kpis.meanAcknowledgementMinutes),'Acquittement'],['MTTR',this.duration(k.kpis.meanResolutionMinutes),'Résolution'],['SLA dépassés',String(k.kpis.slaBreached),'Action requise']];values.forEach((v,index)=>{const col=index%4,row=Math.floor(index/4),x=12+col*47,y=54+row*24;const accent:[number,number,number]=index===1||index===7?[214,69,69]:index===3?[25,135,84]:[8,126,139];doc.setFillColor(255,255,255);doc.setDrawColor(218,229,234);doc.roundedRect(x,y,43,20,2,2,'FD');doc.setFillColor(...accent);doc.rect(x,y,1.5,20,'F');doc.setFontSize(6.5);doc.setFont('helvetica','bold');doc.setTextColor(...this.muted);doc.text(v[0].toUpperCase(),x+4,y+5);doc.setFontSize(13);doc.setTextColor(24,37,46);doc.text(v[1],x+4,y+12);doc.setFontSize(6);doc.setFont('helvetica','normal');doc.setTextColor(...this.muted);doc.text(v[2],x+4,y+17)})}
 private charts(doc:jsPDF,k:ReportingDashboard){this.chart(doc,12,105,90,'Incidents par priorité',k.incidentsByPriority,[214,69,69]);this.chart(doc,108,105,90,'Incidents par statut',k.incidentsByStatus,[8,126,139])}
 private chart(doc:jsPDF,x:number,y:number,width:number,title:string,items:{key:string;count:number}[],color:[number,number,number]){doc.setFillColor(255,255,255);doc.setDrawColor(218,229,234);doc.roundedRect(x,y,width,29,2,2,'FD');doc.setFontSize(8);doc.setFont('helvetica','bold');doc.setTextColor(...this.navy);doc.text(title,x+4,y+6);const visible=items.slice(0,4),max=Math.max(1,...visible.map(i=>i.count));visible.forEach((item,n)=>{const yy=y+11+n*4;doc.setFontSize(5.8);doc.setFont('helvetica','normal');doc.setTextColor(...this.muted);doc.text(this.status(this.priority(item.key)).slice(0,18),x+4,yy);doc.setFillColor(232,239,242);doc.rect(x+34,yy-2.3,width-43,2.5,'F');doc.setFillColor(...color);doc.rect(x+34,yy-2.3,(width-43)*item.count/max,2.5,'F');doc.setFont('helvetica','bold');doc.text(String(item.count),x+width-5,yy,{align:'right'})})}

 private resolutions(doc:jsPDF,items:ReportIncident[]){const resolved=items.filter(i=>i.rootCause||i.correctiveAction||i.resolutionSummary);if(!resolved.length)return;doc.addPage();let y=36;doc.setFont('helvetica','bold');doc.setTextColor(...this.navy);doc.setFontSize(13);doc.text('Causes racines et actions correctives',12,y);y+=8;for(const item of resolved){const lines=[`Cause racine : ${item.rootCause||'Non renseignée'}`,`Action corrective : ${item.correctiveAction||'Non renseignée'}`,`Action préventive : ${item.preventiveAction||'Non renseignée'}`,`Résumé : ${item.resolutionSummary||'Non renseigné'}`].flatMap(x=>doc.splitTextToSize(x,178));const h=13+lines.length*4;if(y+h>277){doc.addPage();y=36}doc.setFillColor(255,255,255);doc.setDrawColor(218,229,234);doc.roundedRect(12,y,186,h,2,2,'FD');doc.setFontSize(8.5);doc.setFont('helvetica','bold');doc.setTextColor(...this.navy);doc.text(`${item.incidentNumber} - ${item.title}`,16,y+6);doc.setFontSize(7.2);doc.setFont('helvetica','normal');doc.setTextColor(24,37,46);doc.text(lines,16,y+12);y+=h+4}}
 private header(doc:jsPDF,logo:string,data:ReportData){doc.setFillColor(...this.navy);doc.rect(8,7,194,21,'F');if(logo)doc.addImage(logo,'JPEG',11,9,17,17);doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('STB SENTINEL',32,16);doc.setFont('helvetica','normal');doc.setFontSize(6.5);doc.text("Supervision des systèmes d'information",32,21);doc.setTextColor(44,181,192);doc.setFont('helvetica','bold');doc.text('PÉRIODE ANALYSÉE',196,14,{align:'right'});doc.setTextColor(255,255,255);doc.setFont('helvetica','normal');doc.text(`${this.date(data.from)} - ${this.date(data.to)}`,196,20,{align:'right'})}
 private footer(doc:jsPDF,page:number,total:number){doc.setDrawColor(216,227,232);doc.line(10,285,200,285);doc.setFontSize(6.5);doc.setTextColor(...this.muted);doc.text('STB Sentinel - Confidentiel - Usage interne',10,290);doc.text(`Page ${page} / ${total}`,200,290,{align:'right'})}

 private async xlsx(k:ReportingDashboard,data:ReportData,period:Period){const wb=new ExcelJS.Workbook();wb.creator='STB Sentinel';const kpi=wb.addWorksheet('KPI',{views:[{showGridLines:false}]});kpi.columns=[{width:30},{width:22},{width:42}];kpi.addRow(['STB SENTINEL',this.title(period),'']);kpi.addRow(['Période',`${this.date(data.from)} - ${this.date(data.to)}`,'']);[['Disponibilité',k.kpis.availability+' %'],['Alertes actives',k.kpis.openAlerts],['Incidents',data.incidents.length],['MTTD',this.duration(k.kpis.meanDetectionMinutes)],['MTTA',this.duration(k.kpis.meanAcknowledgementMinutes)],['MTTR',this.duration(k.kpis.meanResolutionMinutes)],['SLA respecté',k.kpis.slaComplianceRate+' %']].forEach(x=>kpi.addRow(x));this.styleSheet(kpi);
  const incidents=wb.addWorksheet('Incidents',{views:[{state:'frozen',ySplit:1}]});incidents.columns=[{header:'Numéro',key:'number',width:20},{header:'Titre',key:'title',width:42},{header:'Système',key:'system',width:25},{header:'Priorité',key:'priority',width:16},{header:'Statut',key:'status',width:16},{header:'SLA',key:'sla',width:16},{header:'Technicien',key:'technician',width:25},{header:'Création',key:'created',width:21},{header:'Résolution',key:'resolved',width:21},{header:'Cause racine',key:'root',width:45},{header:'Action corrective',key:'corrective',width:45}];data.incidents.forEach(i=>incidents.addRow({number:i.incidentNumber,title:i.title,system:i.systemName,priority:this.priority(i.priority),status:this.status(i.status),sla:this.sla(i.slaStatus),technician:i.technician,created:new Date(i.createdAt),resolved:i.resolvedAt?new Date(i.resolvedAt):null,root:i.rootCause,corrective:i.correctiveAction}));incidents.autoFilter={from:'A1',to:'K1'};this.styleSheet(incidents);
  return new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
 private styleSheet(sheet:ExcelJS.Worksheet){const header=sheet.getRow(1);header.font={bold:true,color:{argb:'FFFFFFFF'}};header.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF123B5D'}};header.height=24;sheet.eachRow((row,n)=>{row.alignment={vertical:'middle',wrapText:true};if(n>1&&n%2===0)row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF0F5F7'}}})}
 private range(period:Period,from:string,to:string){const end=new Date(`${to}T23:59:59`);if(period==='monthly')return{from:`${to.slice(0,7)}-01`,to};if(period==='annual')return{from:`${to.slice(0,4)}-01-01`,to};return{from,to}}
 private title(period:Period){return period==='monthly'?'Rapport mensuel':period==='annual'?'Rapport annuel':'Rapport personnalisé'}
 private priority(x:string){return({P1Critical:'P1 Critique',P2High:'P2 Haute',P3Medium:'P3 Moyenne',P4Low:'P4 Faible'}as any)[x]||x}private status(x:string){return({New:'Nouveau',Assigned:'Affecté',InProgress:'En cours',Pending:'En attente',Resolved:'Résolu',Closed:'Clôturé',Cancelled:'Annulé'}as any)[x]||x}private sla(x:string){return({OnTrack:'Dans les délais',AtRisk:'À risque',Breached:'Dépassé',Met:'Respecté'}as any)[x]||x}private duration(v:number){return v>=60?`${(v/60).toFixed(1)} h`:`${v.toFixed(1)} min`}private date(v:string){return new Date(v).toLocaleDateString('fr-FR')}private dateTime(v:string){return new Date(v).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'})}
 private async logo(){try{const blob=await fetch('/assets/stb-logo.jpg').then(r=>r.blob());return await new Promise<string>((ok,ko)=>{const reader=new FileReader();reader.onload=()=>ok(String(reader.result));reader.onerror=()=>ko(reader.error);reader.readAsDataURL(blob)})}catch{return''}}
}
