using Microsoft.EntityFrameworkCore;
using StbMonitoring.Domain.Entities;
namespace StbMonitoring.Infrastructure.Persistence;
/// <summary>
/// Unité de persistance PostgreSQL du domaine. Les configurations ci-dessous
/// traduisent les relations métier, les suppressions en cascade et les index
/// utilisés par la supervision, la déduplication et les recherches opérationnelles.
/// </summary>
public sealed class MonitoringDbContext(DbContextOptions<MonitoringDbContext> options) : DbContext(options)
{
    public DbSet<User> Users => Set<User>(); public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public DbSet<MonitoredSystem> Systems => Set<MonitoredSystem>(); public DbSet<MonitoringEndpoint> MonitoringEndpoints => Set<MonitoringEndpoint>(); public DbSet<CheckResult> CheckResults => Set<CheckResult>();
    public DbSet<AlertRule> AlertRules=>Set<AlertRule>();public DbSet<Alert> Alerts=>Set<Alert>();public DbSet<AlertOccurrence> AlertOccurrences=>Set<AlertOccurrence>();public DbSet<Incident> Incidents=>Set<Incident>();public DbSet<IncidentComment> IncidentComments=>Set<IncidentComment>();public DbSet<IncidentHistory> IncidentHistories=>Set<IncidentHistory>();public DbSet<IncidentAttachment> IncidentAttachments=>Set<IncidentAttachment>();public DbSet<SlaPolicy> SlaPolicies=>Set<SlaPolicy>();public DbSet<Notification> Notifications=>Set<Notification>();public DbSet<MaintenanceWindow> MaintenanceWindows=>Set<MaintenanceWindow>();
    protected override void OnModelCreating(ModelBuilder b)
    {
        // Le rôle est un champ de User : il n'existe volontairement aucune table
        // roles/user_roles dans le modèle simplifié de la plateforme.
        b.Entity<User>(e=>{e.ToTable("users");e.HasKey(x=>x.Id);e.Property(x=>x.Username).HasMaxLength(80).IsRequired();e.HasIndex(x=>x.Username).IsUnique();e.Property(x=>x.Email).HasMaxLength(180).IsRequired();e.HasIndex(x=>x.Email).IsUnique();e.Property(x=>x.PasswordHash).IsRequired();e.Property(x=>x.Role).HasMaxLength(30).IsRequired();e.Property(x=>x.AvatarPath).HasMaxLength(260);e.Property(x=>x.PhoneNumber).HasMaxLength(30);e.Property(x=>x.JobTitle).HasMaxLength(120);e.Property(x=>x.Skills).HasMaxLength(800);e.Property(x=>x.PasswordResetTokenHash).HasMaxLength(128);e.Property(x=>x.TwoFactorChallengeHash).HasMaxLength(128);e.Property(x=>x.TwoFactorCodeHash).HasMaxLength(128);e.HasIndex(x=>x.Role);});
        b.Entity<AuditLog>(e=>{e.ToTable("audit_logs");e.HasKey(x=>x.Id);e.Property(x=>x.Action).HasMaxLength(100).IsRequired();e.Property(x=>x.EntityName).HasMaxLength(100).IsRequired();});
        b.Entity<MonitoredSystem>(e=>{e.ToTable("monitored_systems");e.HasKey(x=>x.Id);e.Property(x=>x.Code).HasMaxLength(60).IsRequired();e.HasIndex(x=>x.Code).IsUnique();e.Property(x=>x.Name).HasMaxLength(160).IsRequired();e.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20);e.Property(x=>x.Environment).HasConversion<string>().HasMaxLength(30);e.Property(x=>x.Criticality).HasConversion<string>().HasMaxLength(20);e.HasMany(x=>x.Endpoints).WithOne(x=>x.System).HasForeignKey(x=>x.SystemId).OnDelete(DeleteBehavior.Cascade);});
        b.Entity<MonitoringEndpoint>(e=>{e.ToTable("monitoring_endpoints");e.HasKey(x=>x.Id);e.Property(x=>x.Name).HasMaxLength(160).IsRequired();e.Property(x=>x.Url).HasMaxLength(2048).IsRequired();e.Property(x=>x.CheckType).HasConversion<string>().HasMaxLength(20);e.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20);e.HasMany(x=>x.Results).WithOne(x=>x.Endpoint).HasForeignKey(x=>x.EndpointId).OnDelete(DeleteBehavior.Cascade);});
        b.Entity<CheckResult>(e=>{e.ToTable("check_results");e.HasKey(x=>x.Id);e.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20);e.HasOne(x=>x.System).WithMany().HasForeignKey(x=>x.SystemId).OnDelete(DeleteBehavior.Cascade);e.HasIndex(x=>new{x.EndpointId,x.StartedAt});});
        b.Entity<AlertRule>(e=>{e.ToTable("alert_rules");e.HasKey(x=>x.Id);e.Property(x=>x.Name).HasMaxLength(150).IsRequired();e.Property(x=>x.EventType).HasConversion<string>();e.Property(x=>x.Severity).HasConversion<string>();e.HasIndex(x=>x.IsActive);});
        // L'index Status + DeduplicationKey permet de retrouver rapidement une
        // alerte active identique et d'éviter la création de doublons.
        b.Entity<Alert>(e=>{e.ToTable("alerts");e.HasKey(x=>x.Id);e.Property(x=>x.AlertNumber).HasMaxLength(30).IsRequired();e.HasIndex(x=>x.AlertNumber).IsUnique();e.Property(x=>x.Type).HasConversion<string>();e.Property(x=>x.Severity).HasConversion<string>();e.Property(x=>x.Status).HasConversion<string>();e.Property(x=>x.DeduplicationKey).HasMaxLength(250);e.HasIndex(x=>new{x.Status,x.DeduplicationKey});e.HasOne<MonitoredSystem>().WithMany().HasForeignKey(x=>x.SystemId).OnDelete(DeleteBehavior.Restrict);e.HasOne<MonitoringEndpoint>().WithMany().HasForeignKey(x=>x.EndpointId).OnDelete(DeleteBehavior.Restrict);});
        b.Entity<AlertOccurrence>(e=>{e.ToTable("alert_occurrences");e.HasKey(x=>x.Id);e.Property(x=>x.Status).HasConversion<string>();e.HasOne<Alert>().WithMany().HasForeignKey(x=>x.AlertId).OnDelete(DeleteBehavior.Cascade);e.HasOne<CheckResult>().WithMany().HasForeignKey(x=>x.CheckResultId).OnDelete(DeleteBehavior.Restrict);});
        b.Entity<SlaPolicy>(e=>{e.ToTable("sla_policies");e.HasKey(x=>x.Id);e.Property(x=>x.Name).HasMaxLength(150);e.Property(x=>x.Priority).HasConversion<string>();e.HasIndex(x=>new{x.Priority,x.IsActive});});
        b.Entity<Incident>(e=>{e.ToTable("incidents");e.HasKey(x=>x.Id);e.Property(x=>x.IncidentNumber).HasMaxLength(30);e.HasIndex(x=>x.IncidentNumber).IsUnique();e.Property(x=>x.Category).HasConversion<string>();e.Property(x=>x.Priority).HasConversion<string>();e.Property(x=>x.Status).HasConversion<string>();e.Property(x=>x.SlaStatus).HasConversion<string>();e.HasIndex(x=>new{x.Status,x.Priority});e.HasOne<User>().WithMany().HasForeignKey(x=>x.AssignedToUserId).OnDelete(DeleteBehavior.SetNull);});
        b.Entity<IncidentComment>(e=>{e.ToTable("incident_comments");e.HasKey(x=>x.Id);e.HasOne<Incident>().WithMany().HasForeignKey(x=>x.IncidentId).OnDelete(DeleteBehavior.Cascade);e.HasOne<User>().WithMany().HasForeignKey(x=>x.UserId).OnDelete(DeleteBehavior.Restrict);});
        b.Entity<IncidentHistory>(e=>{e.ToTable("incident_history");e.HasKey(x=>x.Id);e.Property(x=>x.Action).HasMaxLength(100);e.HasOne<Incident>().WithMany().HasForeignKey(x=>x.IncidentId).OnDelete(DeleteBehavior.Cascade);});
        b.Entity<IncidentAttachment>(e=>{e.ToTable("incident_attachments");e.HasKey(x=>x.Id);e.Property(x=>x.FileName).HasMaxLength(255);e.Property(x=>x.ContentType).HasMaxLength(120);e.HasOne<Incident>().WithMany().HasForeignKey(x=>x.IncidentId).OnDelete(DeleteBehavior.Cascade);e.HasOne<User>().WithMany().HasForeignKey(x=>x.UploadedByUserId).OnDelete(DeleteBehavior.Restrict);});
        b.Entity<Notification>(e=>{e.ToTable("notifications");e.HasKey(x=>x.Id);e.Property(x=>x.Type).HasMaxLength(50);e.Property(x=>x.Severity).HasConversion<string>();e.HasOne<User>().WithMany().HasForeignKey(x=>x.UserId).OnDelete(DeleteBehavior.Cascade);e.HasIndex(x=>new{x.UserId,x.IsRead,x.CreatedAt});});
        b.Entity<MaintenanceWindow>(e=>{e.ToTable("maintenance_windows");e.HasKey(x=>x.Id);e.Property(x=>x.Title).HasMaxLength(180).IsRequired();e.HasOne<MonitoredSystem>().WithMany().HasForeignKey(x=>x.SystemId).OnDelete(DeleteBehavior.Cascade);e.HasOne<MonitoringEndpoint>().WithMany().HasForeignKey(x=>x.EndpointId).OnDelete(DeleteBehavior.Cascade);e.HasOne<User>().WithMany().HasForeignKey(x=>x.CreatedByUserId).OnDelete(DeleteBehavior.Restrict);e.HasIndex(x=>new{x.StartsAt,x.EndsAt,x.IsCancelled});});
    }
}
