using Microsoft.EntityFrameworkCore;
using StbMonitoring.Application.Contracts;
using StbMonitoring.Application.Interfaces;
using StbMonitoring.Domain.Constants;
using StbMonitoring.Domain.Entities;
namespace StbMonitoring.Infrastructure.Persistence;
/// <summary>Implémentation PostgreSQL des alertes, incidents, SLA et notifications.</summary>
public sealed class OperationsStore(MonitoringDbContext db) : IOperationsStore
{
    public async Task<IReadOnlyCollection<AlertResponse>> GetAlertsAsync(CancellationToken ct) => await (from a in db.Alerts join s in db.Systems on a.SystemId equals s.Id join e in db.MonitoringEndpoints on a.EndpointId equals e.Id orderby a.LastDetectedAt descending select new AlertResponse(a.Id, a.AlertNumber, a.SystemId, s.Name, a.EndpointId, e.Name, a.Type, a.Title, a.Description, a.Severity, a.Status, a.OccurrenceCount, a.FirstDetectedAt, a.LastDetectedAt, a.AcknowledgedAt, a.ResolvedAt, a.IncidentId, a.LastError)).ToArrayAsync(ct);
    public Task<Alert?> GetAlertAsync(Guid id, CancellationToken ct) => db.Alerts.SingleOrDefaultAsync(x => x.Id == id, ct); public async Task<IReadOnlyCollection<Alert>> GetActiveAlertsForEndpointAsync(Guid endpointId, CancellationToken ct) => await db.Alerts.Where(x => x.EndpointId == endpointId && (x.Status == AlertStatus.Open || x.Status == AlertStatus.Acknowledged)).ToArrayAsync(ct); public async Task<IReadOnlyCollection<AlertOccurrenceResponse>> GetOccurrencesAsync(Guid id, CancellationToken ct) => await db.AlertOccurrences.Where(x => x.AlertId == id).OrderByDescending(x => x.DetectedAt).Select(x => new AlertOccurrenceResponse(x.Id, x.CheckResultId, x.Status, x.ErrorType, x.ErrorMessage, x.DetectedAt)).ToArrayAsync(ct); public Task<Alert?> GetDeduplicatedAlertAsync(string key, DateTime since, CancellationToken ct) => db.Alerts.OrderByDescending(x => x.LastDetectedAt).FirstOrDefaultAsync(x => x.DeduplicationKey == key && x.Status != AlertStatus.Closed && x.LastDetectedAt >= since, ct);
    public async Task<IReadOnlyCollection<AlertRule>> GetRulesAsync(CancellationToken ct) => await db.AlertRules.OrderByDescending(x => x.IsActive).ThenBy(x => x.Name).ToArrayAsync(ct); public Task<AlertRule?> GetRuleAsync(Guid id, CancellationToken ct) => db.AlertRules.SingleOrDefaultAsync(x => x.Id == id, ct); public Task<MonitoringEndpoint?> GetEndpointForAlertAsync(Guid id, CancellationToken ct) => db.MonitoringEndpoints.Include(x => x.System).SingleOrDefaultAsync(x => x.Id == id, ct); public async Task<int> ConsecutiveFailuresAsync(Guid endpointId, int max, CancellationToken ct) { var states = await db.CheckResults.Where(x => x.EndpointId == endpointId).OrderByDescending(x => x.StartedAt).Take(max).Select(x => x.Status).ToArrayAsync(ct); return states.TakeWhile(x => x != MonitoringStatus.Up).Count(); }
    public void AddAlert(Alert x) => db.Alerts.Add(x); public void AddOccurrence(AlertOccurrence x) => db.AlertOccurrences.Add(x); public void AddRule(AlertRule x) => db.AlertRules.Add(x); public void RemoveRule(AlertRule x) => db.AlertRules.Remove(x);
    public async Task<IReadOnlyCollection<IncidentResponse>> GetIncidentsAsync(CancellationToken ct) { var incidents = await ProjectIncidents().ToArrayAsync(ct); return incidents.OrderByDescending(x => x.CreatedAt).ToArray(); }
    public Task<Incident?> GetIncidentAsync(Guid id, CancellationToken ct) => db.Incidents.SingleOrDefaultAsync(x => x.Id == id, ct);
    public Task<Incident?> FindCorrelatedIncidentAsync(Guid systemId,DateTime since,CancellationToken ct)=>db.Incidents.OrderByDescending(x=>x.CreatedAt).FirstOrDefaultAsync(x=>!x.IsArchived&&x.SystemId==systemId&&x.CreatedAt>=since&&x.Status!=IncidentStatus.Closed&&x.Status!=IncidentStatus.Resolved&&x.Status!=IncidentStatus.Cancelled,ct);
    public Task<bool> CanAssignIncidentToAsync(Guid userId, CancellationToken ct) => db.Users.AnyAsync(x => x.Id == userId && x.IsActive && x.Role == RoleNames.Technician, ct);
    public Task<bool> HasResolutionProofAsync(Guid incidentId,CancellationToken ct)=>db.IncidentAttachments.AnyAsync(x=>x.IncidentId==incidentId&&x.IsResolutionProof,ct);
    public Task<bool> IsAlertSuppressedAsync(Guid systemId, Guid endpointId, DateTime at, CancellationToken ct) => db.MaintenanceWindows.AnyAsync(x => !x.IsCancelled && x.SuppressAlerts && x.StartsAt <= at && x.EndsAt >= at && (x.EndpointId == endpointId || (x.EndpointId == null && x.SystemId == systemId)), ct);
    public async Task<IncidentDetailResponse?> GetIncidentDetailAsync(Guid id, CancellationToken ct) { var incident = await ProjectIncidents(db.Incidents.Where(x => x.Id == id)).SingleOrDefaultAsync(ct); if (incident is null) return null; var comments = await (from c in db.IncidentComments join u in db.Users on c.UserId equals u.Id where c.IncidentId == id orderby c.CreatedAt descending select new CommentResponse(c.Id, c.UserId, u.FirstName + " " + u.LastName, string.IsNullOrEmpty(u.AvatarPath)?null:"/"+u.AvatarPath.Replace("\\","/").TrimStart('/'), c.Content, c.CommentType, c.IsInternal, c.CreatedAt)).ToArrayAsync(ct); var history = await db.IncidentHistories.Where(x => x.IncidentId == id).OrderByDescending(x => x.CreatedAt).Select(x => new HistoryResponse(x.Id, x.UserId, x.Action, x.OldValue, x.NewValue, x.Details, x.CreatedAt)).ToArrayAsync(ct); return new(incident, comments, history); }
    private IQueryable<IncidentResponse> ProjectIncidents(IQueryable<Incident>? source = null) { var incidents = source ?? db.Incidents; return from i in incidents join s0 in db.Systems on i.SystemId equals s0.Id into sj from s in sj.DefaultIfEmpty() join u0 in db.Users on i.AssignedToUserId equals u0.Id into uj from u in uj.DefaultIfEmpty() select new IncidentResponse(i.Id, i.IncidentNumber, i.AlertId, i.SystemId, i.EndpointId, s == null ? null : s.Name, i.Title, i.Description, i.Category, i.Priority, i.Status, i.SlaStatus, i.AssignedToUserId, u == null ? null : u.FirstName + " " + u.LastName, i.ResponseDueAt, i.ResolutionDueAt, i.ResolvedAt, i.ResolutionSummary, i.RootCause, i.CorrectiveAction, i.PreventiveAction, i.ResolutionEvidence, i.CancellationReason,i.CancelledAt,i.IsArchived,i.ArchivedAt,i.ArchivedByUserId,i.ReopenCount, i.CreatedAt, i.UpdatedAt); }
    public Task<SlaPolicy?> GetSlaForAsync(IncidentPriority priority, CancellationToken ct) => db.SlaPolicies.FirstOrDefaultAsync(x => x.Priority == priority && x.IsActive, ct); public async Task<IReadOnlyCollection<SlaPolicy>> GetSlasAsync(CancellationToken ct) => await db.SlaPolicies.OrderBy(x => x.Priority).ToArrayAsync(ct); public Task<SlaPolicy?> GetSlaAsync(Guid id, CancellationToken ct) => db.SlaPolicies.SingleOrDefaultAsync(x => x.Id == id, ct); public void AddIncident(Incident x) => db.Incidents.Add(x); public void RemoveIncident(Incident x)=>db.Incidents.Remove(x); public void AddComment(IncidentComment x) => db.IncidentComments.Add(x); public void AddHistory(IncidentHistory x) => db.IncidentHistories.Add(x); public void AddSla(SlaPolicy x) => db.SlaPolicies.Add(x);
    public async Task<IReadOnlyCollection<Guid>> GetAdminUserIdsAsync(CancellationToken ct) => await db.Users.Where(x => x.Role == RoleNames.Admin && x.IsActive).Select(x => x.Id).ToArrayAsync(ct);public async Task<IReadOnlyCollection<Guid>> GetActiveUserIdsByRolesAsync(string[] roles,CancellationToken ct)=>await db.Users.Where(x=>x.IsActive&&roles.Contains(x.Role)).Select(x=>x.Id).ToArrayAsync(ct); public async Task<IReadOnlyCollection<Incident>> GetOpenIncidentsAsync(CancellationToken ct) => await db.Incidents.Where(x => !x.IsArchived&&x.Status != IncidentStatus.Resolved && x.Status != IncidentStatus.Closed && x.Status != IncidentStatus.Cancelled).ToArrayAsync(ct); public async Task<IReadOnlyCollection<Notification>> GetNotificationsAsync(Guid userId, CancellationToken ct) => await db.Notifications.Where(x => x.UserId == userId).OrderByDescending(x => x.CreatedAt).Take(100).ToArrayAsync(ct); public Task<Notification?> GetNotificationAsync(Guid id, Guid userId, CancellationToken ct) => db.Notifications.SingleOrDefaultAsync(x => x.Id == id && x.UserId == userId, ct); public void AddNotification(Notification x) => db.Notifications.Add(x);
    public async Task<OperationsSummary> GetSummaryAsync(Guid userId, CancellationToken ct) => new(await db.Alerts.CountAsync(x => x.Status == AlertStatus.Open || x.Status == AlertStatus.Acknowledged, ct), await db.Alerts.CountAsync(x => x.Severity == AlertSeverity.Critical && (x.Status == AlertStatus.Open || x.Status == AlertStatus.Acknowledged), ct), await db.Incidents.CountAsync(x => x.Status != IncidentStatus.Closed && x.Status != IncidentStatus.Resolved && x.Status != IncidentStatus.Cancelled, ct), await db.Incidents.CountAsync(x => x.AssignedToUserId == null && x.Status != IncidentStatus.Closed, ct), await db.Incidents.CountAsync(x => x.SlaStatus == SlaStatus.Breached, ct), await db.Notifications.CountAsync(x => x.UserId == userId && !x.IsRead, ct)); public Task SaveChangesAsync(CancellationToken ct) => db.SaveChangesAsync(ct);
}
