apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stb-monitoring-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/malek11swissi/stb-monitoring.git
    targetRevision: main
    path: infrastructure/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: stb-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
