using StbMonitoring.Application.Contracts;using StbMonitoring.Domain.Entities;
namespace StbMonitoring.Application.Interfaces;
public interface IMonitoringStore
{
 Task<IReadOnlyCollection<MonitoredSystem>> GetSystemsAsync(bool includeArchived,CancellationToken ct);Task<MonitoredSystem?> GetSystemAsync(Guid id,CancellationToken ct);Task<bool> SystemCodeExistsAsync(string code,Guid? excludedId,CancellationToken ct);Task<MonitoringEndpoint?> GetEndpointAsync(Guid id,CancellationToken ct);Task<IReadOnlyCollection<MonitoringEndpoint>> GetDueEndpointsAsync(DateTime now,CancellationToken ct);Task<IReadOnlyCollection<CheckResult>> GetResultsAsync(Guid? systemId,Guid? endpointId,MonitoringStatus? status,DateTime? from,DateTime? to,int take,CancellationToken ct);Task<bool>SystemHasResultsAsync(Guid systemId,CancellationToken ct);Task<bool>EndpointHasResultsAsync(Guid endpointId,CancellationToken ct);void AddSystem(MonitoredSystem system);void RemoveSystem(MonitoredSystem system);void AddEndpoint(MonitoringEndpoint endpoint);void RemoveEndpoint(MonitoringEndpoint endpoint);void AddResult(CheckResult result);Task SaveChangesAsync(CancellationToken ct);
}
public interface ICheckExecutor{CheckType Type{get;}Task<CheckExecution> ExecuteAsync(MonitoringEndpoint endpoint,CancellationToken ct);}
public interface IMonitoringService
{
 Task<IReadOnlyCollection<SystemResponse>> GetSystemsAsync(bool includeArchived,CancellationToken ct);Task<SystemDetailResponse?> GetSystemAsync(Guid id,CancellationToken ct);Task<SystemResponse> CreateSystemAsync(CreateSystemRequest request,CancellationToken ct);Task<SystemResponse> UpdateSystemAsync(Guid id,UpdateSystemRequest request,CancellationToken ct);Task SetMonitoringAsync(Guid id,bool enabled,CancellationToken ct);Task SetArchivedAsync(Guid id,bool archived,CancellationToken ct);Task DeleteSystemAsync(Guid id,CancellationToken ct);Task<EndpointResponse> CreateEndpointAsync(Guid systemId,UpsertEndpointRequest request,CancellationToken ct);Task<EndpointResponse> UpdateEndpointAsync(Guid id,UpsertEndpointRequest request,CancellationToken ct);Task SetEndpointActiveAsync(Guid id,bool active,CancellationToken ct);Task DeleteEndpointAsync(Guid id,CancellationToken ct);Task<CheckResultResponse> ExecuteEndpointAsync(Guid id,bool manually,Guid? userId,CancellationToken ct);Task<int> ExecuteDueChecksAsync(CancellationToken ct);Task<IReadOnlyCollection<CheckResultResponse>> GetResultsAsync(Guid? systemId,Guid? endpointId,MonitoringStatus? status,DateTime? from,DateTime? to,int take,CancellationToken ct);
}
