using StbMonitoring.Application.Contracts;
using StbMonitoring.Domain.Entities;
namespace StbMonitoring.Application.Interfaces;
public interface IOperationsStore
{
    Task<IReadOnlyCollection<AlertResponse>> GetAlertsAsync(CancellationToken ct); Task<Alert?> GetAlertAsync(Guid id, CancellationToken ct); Task<IReadOnlyCollection<Alert>> GetActiveAlertsForEndpointAsync(Guid endpointId, CancellationToken ct); Task<IReadOnlyCollection<AlertOccurrenceResponse>> GetOccurrencesAsync(Guid id, CancellationToken ct); Task<Alert?> GetDeduplicatedAlertAsync(string key, DateTime since, CancellationToken ct); Task<IReadOnlyCollection<AlertRule>> GetRulesAsync(CancellationToken ct); Task<AlertRule?> GetRuleAsync(Guid id, CancellationToken ct); Task<MonitoringEndpoint?> GetEndpointForAlertAsync(Guid id, CancellationToken ct); Task<int> ConsecutiveFailuresAsync(Guid endpointId, int max, CancellationToken ct); Task<bool> IsAlertSuppressedAsync(Guid systemId, Guid endpointId, DateTime at, CancellationToken ct); void AddAlert(Alert x); void AddOccurrence(AlertOccurrence x); void AddRule(AlertRule x); void RemoveRule(AlertRule x);
    Task<IReadOnlyCollection<IncidentResponse>> GetIncidentsAsync(CancellationToken ct); Task<Incident?> GetIncidentAsync(Guid id, CancellationToken ct); Task<Incident?> FindCorrelatedIncidentAsync(Guid systemId,DateTime since,CancellationToken ct); Task<IncidentDetailResponse?> GetIncidentDetailAsync(Guid id, CancellationToken ct); Task<bool> CanAssignIncidentToAsync(Guid userId, CancellationToken ct); Task<bool> HasResolutionProofAsync(Guid incidentId,CancellationToken ct); Task<SlaPolicy?> GetSlaForAsync(IncidentPriority priority, CancellationToken ct); Task<IReadOnlyCollection<SlaPolicy>> GetSlasAsync(CancellationToken ct); Task<SlaPolicy?> GetSlaAsync(Guid id,CancellationToken ct); void AddIncident(Incident x); void RemoveIncident(Incident x); void AddComment(IncidentComment x); void AddHistory(IncidentHistory x); void AddSla(SlaPolicy x);
    Task<IReadOnlyCollection<Guid>> GetAdminUserIdsAsync(CancellationToken ct); Task<IReadOnlyCollection<Guid>> GetActiveUserIdsByRolesAsync(string[] roles,CancellationToken ct); Task<IReadOnlyCollection<Incident>> GetOpenIncidentsAsync(CancellationToken ct); Task<IReadOnlyCollection<Notification>> GetNotificationsAsync(Guid userId, CancellationToken ct); Task<Notification?> GetNotificationAsync(Guid id, Guid userId, CancellationToken ct); void AddNotification(Notification x); Task<OperationsSummary> GetSummaryAsync(Guid userId, CancellationToken ct); Task SaveChangesAsync(CancellationToken ct);
}
public interface IOperationsService
{
    Task EvaluateAsync(CheckResult result, CancellationToken ct); Task<IReadOnlyCollection<AlertResponse>> AlertsAsync(CancellationToken ct); Task<AlertDetailResponse?> AlertAsync(Guid id, CancellationToken ct); Task AcknowledgeAsync(Guid id, Guid userId, CancellationToken ct); Task ResolveAlertAsync(Guid id, CancellationToken ct); Task CloseAlertAsync(Guid id, Guid userId, CancellationToken ct);
    Task<IReadOnlyCollection<AlertRuleResponse>> RulesAsync(CancellationToken ct); Task<AlertRuleResponse> CreateRuleAsync(AlertRuleRequest r, CancellationToken ct); Task<AlertRuleResponse> UpdateRuleAsync(Guid id, AlertRuleRequest r, CancellationToken ct); Task SetRuleActiveAsync(Guid id, bool value, CancellationToken ct); Task DeleteRuleAsync(Guid id, CancellationToken ct);
    Task<IReadOnlyCollection<IncidentResponse>> IncidentsAsync(CancellationToken ct); Task<IncidentDetailResponse?> IncidentAsync(Guid id, CancellationToken ct); Task<IncidentResponse> CreateIncidentAsync(CreateIncidentRequest r, Guid actor, CancellationToken ct); Task<IncidentResponse> UpdateIncidentAsync(Guid id, UpdateIncidentRequest r, Guid actor, CancellationToken ct); Task AssignAsync(Guid id, Guid userId, Guid actor, CancellationToken ct); Task StartAsync(Guid id, Guid actor, CancellationToken ct); Task PendingAsync(Guid id, Guid actor, CancellationToken ct); Task ResolveIncidentAsync(Guid id, ResolveIncidentRequest r, Guid actor, CancellationToken ct); Task CloseIncidentAsync(Guid id, Guid actor, CancellationToken ct); Task ReopenAsync(Guid id, Guid actor, CancellationToken ct); Task CancelIncidentAsync(Guid id,string reason,Guid actor,CancellationToken ct); Task ArchiveIncidentAsync(Guid id,Guid actor,CancellationToken ct); Task RestoreIncidentAsync(Guid id,Guid actor,CancellationToken ct); Task DeleteIncidentAsync(Guid id,string reason,Guid actor,CancellationToken ct); Task CommentAsync(Guid id, AddCommentRequest r, Guid actor, CancellationToken ct);
    Task<IReadOnlyCollection<SlaPolicyResponse>> SlasAsync(CancellationToken ct); Task<SlaPolicyResponse> CreateSlaAsync(SlaPolicyRequest r, CancellationToken ct); Task<SlaPolicyResponse> UpdateSlaAsync(Guid id, SlaPolicyRequest r, CancellationToken ct); Task SetSlaActiveAsync(Guid id, bool value, CancellationToken ct); Task RefreshSlasAsync(CancellationToken ct); Task<IReadOnlyCollection<NotificationResponse>> NotificationsAsync(Guid userId, CancellationToken ct); Task ReadNotificationAsync(Guid id, Guid userId, CancellationToken ct); Task ReadAllAsync(Guid userId, CancellationToken ct); Task<OperationsSummary> SummaryAsync(Guid userId, CancellationToken ct);
}
