using StbMonitoring.Application.Contracts;
using StbMonitoring.Application.Interfaces;
using StbMonitoring.Domain.Entities;
namespace StbMonitoring.Application.Services;
/// <summary>
/// Orchestre le catalogue des SI et l'exécution de leurs points de contrôle.
/// Une exécution produit toujours un CheckResult historisé, met à jour l'état
/// de l'endpoint puis celui du SI, et transmet enfin le résultat au moteur d'alertes.
/// </summary>
public sealed class MonitoringService(IMonitoringStore store,IEnumerable<ICheckExecutor> executors,IOperationsService operations):IMonitoringService
{
 public async Task<IReadOnlyCollection<SystemResponse>> GetSystemsAsync(bool archived,CancellationToken ct)=>(await store.GetSystemsAsync(archived,ct)).Select(Map).ToArray();
 public async Task<SystemDetailResponse?> GetSystemAsync(Guid id,CancellationToken ct){var s=await store.GetSystemAsync(id,ct);if(s is null)return null;var results=await store.GetResultsAsync(id,null,null,null,null,100,ct);return new(Map(s),s.Endpoints.Select(Map).ToArray(),results.Select(Map).ToArray());}
 public async Task<SystemResponse>CreateSystemAsync(CreateSystemRequest r,CancellationToken ct){if(await store.SystemCodeExistsAsync(r.Code,null,ct))throw new InvalidOperationException("Ce code système existe déjà.");var s=new MonitoredSystem(r.Code,r.Name,r.Description,r.Environment,r.Criticality,r.Owner);store.AddSystem(s);await store.SaveChangesAsync(ct);return Map(s);}
 public async Task<SystemResponse>UpdateSystemAsync(Guid id,UpdateSystemRequest r,CancellationToken ct){var s=await RequiredSystem(id,ct);if(await store.SystemCodeExistsAsync(r.Code,id,ct))throw new InvalidOperationException("Ce code système existe déjà.");s.Update(r.Code,r.Name,r.Description,r.Environment,r.Criticality,r.Owner);await store.SaveChangesAsync(ct);return Map(s);}
 public async Task SetMonitoringAsync(Guid id,bool enabled,CancellationToken ct){var s=await RequiredSystem(id,ct);if(enabled&&s.IsArchived)throw new InvalidOperationException("Restaurez le système avant d'activer sa supervision.");s.SetMonitoring(enabled);await store.SaveChangesAsync(ct);}public async Task SetArchivedAsync(Guid id,bool archived,CancellationToken ct){var s=await RequiredSystem(id,ct);if(archived)s.Archive();else s.Restore();await store.SaveChangesAsync(ct);}
 // Un SI possédant des résultats est archivé plutôt que supprimé : ses preuves
 // techniques doivent rester disponibles pour l'audit et les rapports.
 public async Task DeleteSystemAsync(Guid id,CancellationToken ct){var s=await RequiredSystem(id,ct);if(await store.SystemHasResultsAsync(id,ct))throw new InvalidOperationException("Ce système possède un historique. Archivez-le au lieu de le supprimer.");store.RemoveSystem(s);await store.SaveChangesAsync(ct);}
 public async Task<EndpointResponse>CreateEndpointAsync(Guid systemId,UpsertEndpointRequest r,CancellationToken ct){var system=await RequiredSystem(systemId,ct);if(system.IsArchived)throw new InvalidOperationException("Impossible d'ajouter un endpoint à un système archivé.");Validate(r);var e=New(systemId,r);store.AddEndpoint(e);await store.SaveChangesAsync(ct);return Map(e);}public async Task<EndpointResponse>UpdateEndpointAsync(Guid id,UpsertEndpointRequest r,CancellationToken ct){var e=await RequiredEndpoint(id,ct);Validate(r);e.Update(r.Name,r.Url,r.CheckType,r.HttpMethod,r.ExpectedStatusCode,r.TimeoutSeconds,r.IntervalSeconds,r.DegradedThresholdMs,r.DownThresholdMs,r.IsCritical,r.ExpectedJsonProperty,r.ExpectedJsonValue);await store.SaveChangesAsync(ct);return Map(e);}public async Task SetEndpointActiveAsync(Guid id,bool active,CancellationToken ct){var e=await RequiredEndpoint(id,ct);e.SetActive(active);e.System.RecalculateStatus();await store.SaveChangesAsync(ct);}public async Task DeleteEndpointAsync(Guid id,CancellationToken ct){var e=await RequiredEndpoint(id,ct);if(await store.EndpointHasResultsAsync(id,ct))throw new InvalidOperationException("Cet endpoint possède un historique et ne peut pas être supprimé.");store.RemoveEndpoint(e);await store.SaveChangesAsync(ct);}
 /// <summary>
 /// Exécute un contrôle manuel ou planifié. Le type configuré sélectionne
 /// l'exécuteur HTTP, API JSON ou TLS approprié.
 /// </summary>
 public async Task<CheckResultResponse>ExecuteEndpointAsync(Guid id,bool manually,Guid? userId,CancellationToken ct){var e=await RequiredEndpoint(id,ct);if(!e.IsActive)throw new InvalidOperationException("Endpoint désactivé.");var executor=executors.FirstOrDefault(x=>x.Type==e.CheckType)??throw new NotSupportedException($"Contrôle {e.CheckType} non supporté.");var x=await executor.ExecuteAsync(e,ct);e.Record(x.Status,x.DurationMs,x.ErrorMessage);var result=new CheckResult(e.SystemId,e.Id,x.Status,x.Success,x.StartedAt,x.CompletedAt,x.DurationMs,x.HttpStatusCode,x.ErrorType,x.ErrorMessage,manually,userId,x.Metadata);store.AddResult(result);await store.SaveChangesAsync(ct);var system=await RequiredSystem(e.SystemId,ct);system.RecalculateStatus();await store.SaveChangesAsync(ct);
 // L'évaluation vient après la sauvegarde : une alerte référence ainsi une
 // preuve technique déjà persistée et téléchargeable.
 await operations.EvaluateAsync(result,ct);return Map(result,e.Name);}
 /// <summary>Exécute uniquement les endpoints actifs dont NextCheckAt est arrivé.</summary>
 public async Task<int>ExecuteDueChecksAsync(CancellationToken ct){var due=await store.GetDueEndpointsAsync(DateTime.UtcNow,ct);var count=0;foreach(var endpoint in due){try{await ExecuteEndpointAsync(endpoint.Id,false,null,ct);count++;}catch when(!ct.IsCancellationRequested){/* Un endpoint en échec ne doit pas bloquer les autres SI du cycle. */}}return count;}
 public async Task<IReadOnlyCollection<CheckResultResponse>>GetResultsAsync(Guid? systemId,Guid? endpointId,MonitoringStatus? status,DateTime? from,DateTime? to,int take,CancellationToken ct){if(from.HasValue&&to.HasValue&&from>to)throw new ArgumentException("La date de début doit précéder la date de fin.");return(await store.GetResultsAsync(systemId,endpointId,status,from,to,Math.Clamp(take,1,500),ct)).Select(Map).ToArray();}
 private async Task<MonitoredSystem>RequiredSystem(Guid id,CancellationToken ct)=>await store.GetSystemAsync(id,ct)??throw new KeyNotFoundException("Système introuvable.");private async Task<MonitoringEndpoint>RequiredEndpoint(Guid id,CancellationToken ct)=>await store.GetEndpointAsync(id,ct)??throw new KeyNotFoundException("Endpoint introuvable.");private static void Validate(UpsertEndpointRequest r){if(!Uri.TryCreate(r.Url,UriKind.Absolute,out var uri)||uri.Scheme is not("http"or"https"))throw new ArgumentException("URL HTTP/HTTPS invalide.");if(r.DownThresholdMs<r.DegradedThresholdMs)throw new ArgumentException("Le seuil DOWN doit être supérieur au seuil DEGRADED.");}
 private static MonitoringEndpoint New(Guid id,UpsertEndpointRequest r)=>new(id,r.Name,r.Url,r.CheckType,r.HttpMethod,r.ExpectedStatusCode,r.TimeoutSeconds,r.IntervalSeconds,r.DegradedThresholdMs,r.DownThresholdMs,r.IsCritical,r.ExpectedJsonProperty,r.ExpectedJsonValue);
 private static SystemResponse Map(MonitoredSystem s)=>new(s.Id,s.Code,s.Name,s.Description,s.Environment,s.Criticality,s.Owner,s.MonitoringEnabled,s.IsArchived,s.Status,s.LastCheckedAt,s.Endpoints.Count,s.Endpoints.Count(x=>x.Status==MonitoringStatus.Up),s.Endpoints.Count(x=>x.Status==MonitoringStatus.Degraded),s.Endpoints.Count(x=>x.Status==MonitoringStatus.Down));private static EndpointResponse Map(MonitoringEndpoint e)=>new(e.Id,e.SystemId,e.Name,e.Url,e.CheckType,e.HttpMethod,e.ExpectedStatusCode,e.TimeoutSeconds,e.IntervalSeconds,e.DegradedThresholdMs,e.DownThresholdMs,e.IsCritical,e.IsActive,e.ExpectedJsonProperty,e.ExpectedJsonValue,e.Status,e.LastCheckedAt,e.NextCheckAt,e.LastDurationMs,e.LastError);private static CheckResultResponse Map(CheckResult r)=>Map(r,r.Endpoint?.Name??string.Empty);private static CheckResultResponse Map(CheckResult r,string name)=>new(r.Id,r.SystemId,r.EndpointId,name,r.Status,r.Success,r.StartedAt,r.CompletedAt,r.DurationMs,r.HttpStatusCode,r.ErrorType,r.ErrorMessage,r.TriggeredManually,r.TriggeredByUserId,r.Metadata);
}
