/** Administration dédiée des règles d'alerte, sans exposer les alertes opérationnelles. */
import {Component,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {AlertRule,OperationsService} from '../core/operations.service';

@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="page rules-page"><header><div><span>CONFIGURATION DES ALERTES</span><h1>Règles de détection</h1><p>Définissez quand une anomalie devient une alerte opérationnelle.</p></div><button class="primary" (click)="create()">＋ Nouvelle règle</button></header>
@if(error){<div class="error">{{error}}</div>}@if(message){<div class="success">{{message}}</div>}
<div class="rules-grid">@for(r of rules;track r.id){<article class="card rule" [class.inactive]="!r.isActive"><div class="rule-head"><span [class]="'event '+r.severity.toLowerCase()">{{r.eventType}}</span><span [class]="r.isActive?'state on':'state'">● {{r.isActive?'Active':'Inactive'}}</span></div><h2>{{r.name}}</h2><p>{{r.description||'Aucune description'}}</p><dl><div><dt>Sévérité</dt><dd>{{r.severity}}</dd></div><div><dt>Confirmation</dt><dd>{{r.consecutiveFailures}} échec(s)</dd></div><div><dt>Déduplication</dt><dd>{{r.deduplicationMinutes}} min</dd></div><div><dt>Résolution auto.</dt><dd>{{r.autoResolve?'Oui':'Non'}}</dd></div></dl><footer><button (click)="edit(r)">✎ Modifier</button><button (click)="toggle(r)">{{r.isActive?'◉ Désactiver':'✓ Activer'}}</button><button class="danger" (click)="remove(r)">⌫ Supprimer</button></footer></article>}@empty{<div class="card empty">Aucune règle configurée.</div>}</div>
@if(draft){<div class="modal-backdrop" (click)="draft=null"><form #form="ngForm" class="card modal form" (click)="$event.stopPropagation()" (ngSubmit)="save()"><div class="modal-head"><div><span>RÈGLE D'ALERTE</span><h2>{{editing?'Modifier':'Créer'}} une règle</h2></div><button type="button" (click)="draft=null">×</button></div><label>Nom<input name="name" [(ngModel)]="draft.name" required></label><label>Description<textarea name="description" [(ngModel)]="draft.description"></textarea></label><div class="two"><label>Événement<select name="event" [(ngModel)]="draft.eventType"><option>EndpointDown</option><option>EndpointDegraded</option><option>Timeout</option><option>TlsInvalid</option><option>TlsExpiring</option><option>TlsExpired</option><option>ValidationFailed</option></select></label><label>Sévérité<select name="severity" [(ngModel)]="draft.severity"><option>Critical</option><option>Major</option><option>Warning</option><option>Minor</option><option>Info</option></select></label></div><div class="two"><label>Échecs consécutifs<input type="number" name="failures" [(ngModel)]="draft.consecutiveFailures" min="1" required></label><label>Déduplication (minutes)<input type="number" name="dedup" [(ngModel)]="draft.deduplicationMinutes" min="1" required></label></div><label class="check"><input type="checkbox" name="auto" [(ngModel)]="draft.autoResolve"> Résoudre automatiquement après retour stable</label><label class="check"><input type="checkbox" name="notify" [(ngModel)]="draft.notifyInApp"> Créer une notification interne</label><div class="modal-actions"><button type="button" (click)="draft=null">Annuler</button><button class="primary" [disabled]="form.invalid">Enregistrer</button></div></form></div>}
</section>`,styles:[`
.rules-page{max-width:1250px}.rules-page>header{display:flex;align-items:end;justify-content:space-between;margin-bottom:24px}.rules-page header span,.modal-head span{font-size:10px;font-weight:900;letter-spacing:.15em;color:#087e8b}.rules-page h1{font-size:34px;color:#123b5d;margin:5px 0}.rules-page header p{margin:0;color:#61727e}.rules-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:15px}.rule{border-top:4px solid #087e8b}.rule.inactive{opacity:.68;border-top-color:#94a3b8}.rule-head,footer,.two,.modal-head,.modal-actions{display:flex;justify-content:space-between;gap:10px}.event,.state{font-size:11px;font-weight:800;padding:6px 9px;border-radius:8px;background:#edf4f5}.event.critical{background:#feeceb;color:#b42318}.event.major{background:#fff0e6;color:#b94b0a}.state.on{background:#e7f7ee;color:#087443}.rule h2{font-size:20px;margin:16px 0 6px}.rule p{color:#61727e;min-height:38px}.rule dl{display:grid;grid-template-columns:1fr 1fr;gap:9px}.rule dl div{background:#f5f8fa;padding:10px;border-radius:9px}.rule dt{font-size:10px;color:#718493}.rule dd{margin:4px 0 0;font-weight:800}.rule footer{margin-top:15px}.rule footer button{border:1px solid #d6e1e7;background:#fff;border-radius:8px;padding:8px 10px}.rule footer .danger{color:#b42318}.form{display:grid;gap:13px;width:min(640px,95vw)}.form label{display:grid;gap:6px}.form input,.form textarea,.form select{padding:10px;border:1px solid #cad7df;border-radius:9px}.check{display:flex!important;grid-template-columns:auto 1fr;align-items:center}.modal-actions{justify-content:flex-end}.empty{text-align:center;color:#718493}@media(max-width:600px){.rules-page>header,.two{display:grid;gap:12px}.rules-grid{grid-template-columns:1fr}}
`]})
export class AlertRulesComponent implements OnInit{
 rules:AlertRule[]=[];draft:any=null;editing:AlertRule|null=null;error='';message='';constructor(private api:OperationsService){}ngOnInit(){this.load()}load(){this.api.rules().subscribe({next:x=>this.rules=x,error:e=>this.fail(e)})}
 create(){this.editing=null;this.draft={name:'',description:'',eventType:'EndpointDown',severity:'Major',consecutiveFailures:2,deduplicationMinutes:30,autoResolve:true,notifyInApp:true,systemId:null,endpointId:null}}
 edit(r:AlertRule){this.editing=r;this.draft={...r}}save(){this.request(this.api.saveRule(this.draft,this.editing?.id),'Règle enregistrée.',()=>this.draft=null)}toggle(r:AlertRule){this.request(this.api.ruleActive(r.id,!r.isActive),`Règle ${r.isActive?'désactivée':'activée'}.`)}remove(r:AlertRule){if(confirm(`Supprimer la règle « ${r.name} » ?`))this.request(this.api.deleteRule(r.id),'Règle supprimée.')}
 request(call:any,msg:string,after?:()=>void){this.error='';call.subscribe({next:()=>{after?.();this.message=msg;this.load()},error:(e:any)=>this.fail(e)})}fail(e:any){this.error=e.error?.message||`Erreur HTTP ${e.status||0}`}
}
