/** Liste paginée des incidents avec un jeu de filtres volontairement adapté à chaque rôle. */
import {Component,OnDestroy,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {RouterLink} from '@angular/router';
import {OperationsService,Incident} from '../core/operations.service';
import {AuthService} from '../core/auth.service';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink],styleUrls:['./incidents.extra.css'],template:`
<section class="page incidents">
  <header class="head"><div><span class="eyebrow">GESTION DES INCIDENTS</span><h1>{{isTechnician?'Mes interventions':'Centre de résolution'}}</h1><p>{{isTechnician?'Uniquement les incidents qui vous sont affectés.':'Les incidents sont créés automatiquement depuis les alertes confirmées.'}}</p></div></header>
  <section class="kpis"><button class="today-card" (click)="openToday()"><span class="kpi-icon">◷</span><small>Incidents aujourd'hui</small><b>{{todayTotal}}</b><em>{{isTechnician?'Affectés à votre compte':'Créés depuis minuit'}}</em><i>Voir la liste →</i></button><article><small>Résultats affichés</small><b>{{total}}</b><span>Selon votre périmètre</span></article></section>
  <section class="toolbar card">
    <div class="searchbox"><span>⌕</span><input [(ngModel)]="search" (ngModelChange)="searchChanged()" placeholder="Numéro ou titre"></div>
    <select [(ngModel)]="status" (ngModelChange)="filtersChanged()"><option value="">Tous les statuts</option><option>New</option><option>Assigned</option><option>InProgress</option><option>Pending</option><option>Resolved</option><option>Closed</option><option>Cancelled</option></select>
    @if(isManager){<select [(ngModel)]="priority" (ngModelChange)="filtersChanged()"><option value="">Toutes les priorités</option><option>P1Critical</option><option>P2High</option><option>P3Medium</option><option>P4Low</option></select><select [(ngModel)]="sla" (ngModelChange)="filtersChanged()"><option value="">Tous les SLA</option><option>OnTrack</option><option>AtRisk</option><option>Breached</option><option>Met</option></select>}
    @if(isSupervisor){<select [(ngModel)]="assignment" (ngModelChange)="filtersChanged()"><option value="">Toute affectation</option><option value="unassigned">Non affectés</option><option value="assigned">Affectés</option></select>}
    @if(hasFilters){<button class="clear" (click)="reset()"><span>↻</span> Réinitialiser</button>}
  </section>
  <div class="result-line"><span><b>{{total}}</b> incident{{total>1?'s':''}}</span><small>Page {{page}} sur {{totalPages||1}}</small></div>
  <section class="table card">
    <div class="table-head"><span>Incident</span><span>Système</span><span>Priorité</span><span>Responsable</span><span>SLA</span><span>Statut</span></div>
    @for(i of items;track i.id){<a class="row" [routerLink]="['/incidents',i.id]"><div><b>{{i.incidentNumber}}</b><small>{{i.title}}</small></div><span>{{i.systemName||'Non renseigné'}}</span><span [class]="'pill '+i.priority.toLowerCase()">{{i.priority}}</span><span>{{i.assignedToName||'Non affecté'}}</span><span [class]="'pill '+i.slaStatus.toLowerCase()">{{i.slaStatus}}</span><span class="pill">{{i.status}}</span></a>}
    @empty{<div class="empty"><span>⌕</span><h3>Aucun incident trouvé</h3><p>Modifiez la recherche ou réinitialisez les filtres.</p></div>}
  </section>
  <nav class="pagination"><button [disabled]="page<=1" (click)="go(page-1)">← Précédent</button>@for(p of pages;track p){<button [class.active]="p===page" (click)="go(p)">{{p}}</button>}<button [disabled]="page>=totalPages" (click)="go(page+1)">Suivant →</button></nav>
  @if(error){<div class="error">{{error}}</div>}@if(showToday){<div class="modal-backdrop" (click)="showToday=false"><section class="card today-modal" (click)="$event.stopPropagation()"><header><div><span class="eyebrow">AUJOURD'HUI</span><h2>Incidents créés depuis minuit</h2><p>{{todayItems.length}} incident{{todayItems.length>1?'s':''}} dans votre périmètre</p></div><button (click)="showToday=false">×</button></header><div class="today-list">@for(i of todayItems;track i.id){<a [routerLink]="['/incidents',i.id]" (click)="showToday=false"><span [class]="'today-priority '+i.priority.toLowerCase()">{{priorityLabel(i.priority)}}</span><div><b>{{i.incidentNumber}} · {{i.title}}</b><small>{{i.systemName||'Système non renseigné'}} · {{i.createdAt|date:'HH:mm'}}</small></div><span [class]="'today-status '+i.status.toLowerCase()">{{statusLabel(i.status)}}</span><i>›</i></a>}@empty{<div class="today-empty">✓ Aucun incident créé aujourd'hui.</div>}</div></section></div>}
</section>`,styles:[`
.incidents{max-width:1340px}.head{display:flex;justify-content:space-between;align-items:end;margin-bottom:22px}.head h1{font-size:34px;margin:5px 0}.head p{margin:0;color:#61727e}.eyebrow{font-size:10px;font-weight:900;letter-spacing:.15em;color:#087e8b}.toolbar{display:flex;gap:9px;align-items:center;padding:12px;flex-wrap:wrap}.searchbox{display:flex;align-items:center;gap:8px;flex:1;min-width:250px;border:1px solid #cbd9df;border-radius:10px;padding:0 11px}.searchbox input{border:0;outline:0;width:100%}.toolbar select{min-width:155px}.clear{min-height:42px;border:1px solid #b9d7da;border-radius:9px;background:#eef9f8;color:#087e76;font-weight:800;padding:0 13px}.result-line{display:flex;justify-content:space-between;padding:15px 2px;color:#61727e}.table{padding:0;overflow:hidden}.table-head,.row{display:grid;grid-template-columns:1.4fr 1fr .8fr 1fr .8fr .8fr;gap:10px;align-items:center;padding:15px 18px}.table-head{background:#f3f7f8;font-size:11px;font-weight:900;color:#526873;letter-spacing:.04em}.row{border-top:1px solid #e5ecef;text-decoration:none;color:#203746;transition:.15s}.row:hover{background:#f2fbfb}.row div{display:grid}.row small{color:#718493;font-size:12px;margin-top:3px}.pill{width:max-content;background:#edf3f5;border-radius:20px;padding:5px 9px;font-size:11px;font-weight:700}.pill.p1critical,.pill.breached{background:#feeceb;color:#b42318}.pill.p2high,.pill.atrisk{background:#fff3d9;color:#9a5b00}.pagination{display:flex;justify-content:center;gap:6px;margin-top:18px}.pagination button{border:1px solid #d5e1e5;background:#fff;border-radius:9px;padding:9px 12px}.pagination button.active{background:#087e8b;color:#fff;border-color:#087e8b}.empty{text-align:center;padding:45px;color:#718493}.empty>span{font-size:30px}@media(max-width:900px){.table-head{display:none}.row{grid-template-columns:1fr 1fr}}@media(max-width:550px){.toolbar>*{width:100%}.pagination button:not(:first-child):not(:last-child){display:none}}
`]})
export class IncidentsComponent implements OnInit,OnDestroy{
 items:Incident[]=[];todayItems:Incident[]=[];showToday=false;search='';priority='';status='';sla='';assignment='';error='';page=1;pageSize=15;total=0;todayTotal=0;totalPages=0;private timer?:ReturnType<typeof setTimeout>;
 constructor(public auth:AuthService,private api:OperationsService){}
 get role(){return this.auth.currentUser()?.role}get isTechnician(){return this.role==='TECHNICIAN'}get isSupervisor(){return this.role==='SUPERVISOR'}get isManager(){return this.role==='MANAGER_IT'}get hasFilters(){return!!(this.search||this.priority||this.status||this.sla||this.assignment)}
 get pages(){const start=Math.max(1,this.page-2),end=Math.min(this.totalPages,start+4);return Array.from({length:Math.max(0,end-start+1)},(_,i)=>start+i)}
 ngOnInit(){this.load()}ngOnDestroy(){if(this.timer)clearTimeout(this.timer)}
 load(){this.error='';this.api.incidentsPaged({page:this.page,pageSize:this.pageSize,search:this.search,status:this.status,priority:this.priority,sla:this.sla,assignment:this.assignment}).subscribe({next:x=>{this.items=x.items;this.total=x.total;this.todayTotal=x.todayTotal||0;this.totalPages=x.totalPages},error:e=>this.error=e.error?.message||`Erreur ${e.status}`})}
 searchChanged(){if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>this.filtersChanged(),300)}filtersChanged(){this.page=1;this.load()}go(page:number){if(page>=1&&page<=this.totalPages){this.page=page;this.load()}}reset(){this.search=this.priority=this.status=this.sla=this.assignment='';this.filtersChanged()}openToday(){this.api.incidentsPaged({page:1,pageSize:100}).subscribe({next:x=>{const today=new Date();this.todayItems=x.items.filter(i=>{const d=new Date(i.createdAt);return d.getFullYear()===today.getFullYear()&&d.getMonth()===today.getMonth()&&d.getDate()===today.getDate()});this.showToday=true},error:e=>this.error=e.error?.message||`Erreur ${e.status}`})}priorityLabel(x:string){return({P1Critical:'P1',P2High:'P2',P3Medium:'P3',P4Low:'P4'}as any)[x]||x}statusLabel(x:string){return({New:'Nouveau',Assigned:'Affecté',InProgress:'En cours',Pending:'En attente',Resolved:'Résolu',Closed:'Clôturé',Cancelled:'Annulé'}as any)[x]||x}
}
