/** Profil enrichi : identité, avatar sécurisé, compétences, badge et mot de passe. */
import {Component} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {CommonModule} from '@angular/common';
import {HttpClient} from '@angular/common/http';
import {AuthService,User} from '../core/auth.service';
import {API_ROOT} from '../core/api-url';
@Component({standalone:true,imports:[FormsModule,CommonModule],styleUrls:['./profile.performance.css','./profile.actions.css'],template:`
<section class="page profile-page">
 <header class="profile-hero card"><div class="avatar-wrap"><img [src]="avatarSource" alt="Photo de profil" class="avatar"><label class="avatar-action" title="Modifier la photo">📷<input type="file" accept="image/jpeg,image/png,image/webp" (change)="selectAvatar($event)"></label></div><div class="identity"><span class="eyebrow">MON ESPACE</span><h1>{{firstName}} {{lastName}}</h1><p>{{roleLabel}} · {{email}}</p><div class="profile-tags"><span class="badge achievement">🏅 {{user?.badge || 'Membre'}}</span>@if(user?.role==='TECHNICIAN'){<span class="badge">{{user?.resolvedIncidents || 0}} incidents résolus</span>}</div></div></header>
 <div class="avatar-toolbar"><p class="upload-help">Photo JPG, PNG ou WebP — 2 Mo maximum. Une image par défaut est utilisée sans photo.</p>@if(user?.avatarUrl){<button class="avatar-delete" type="button" (click)="confirmAvatarDelete=true"><span class="trash-icon">⌫</span><span><b>Supprimer la photo</b><small>Revenir à l’avatar par défaut</small></span></button>}</div>
 @if(message){<p class="success">{{message}}</p>}@if(error){<p class="error">{{error}}</p>}
 @if(user?.technicianPerformance;as performance){<section class="performance-shell"><header><div><span class="performance-eyebrow">PARCOURS TECHNICIEN</span><h2>Progression opérationnelle</h2><p>Calculée à partir de vos incidents réellement résolus.</p></div><div class="level-orbit"><span>NIVEAU</span><b>{{performance.level}}</b></div></header><div class="performance-kpis"><article><span class="kpi-symbol">✓</span><div><small>INCIDENTS RÉSOLUS</small><b>{{performance.resolvedIncidents}}</b><em>Interventions terminées</em></div></article><article><span class="kpi-symbol sla-symbol">◷</span><div><small>RESPECT DU SLA</small><b>{{performance.slaComplianceRate|number:'1.0-1'}} %</b><em>Résolutions dans le délai</em></div></article><article><span class="kpi-symbol specialty-symbol">◆</span><div><small>SPÉCIALITÉ PRINCIPALE</small><b class="specialty-value">{{performance.primarySpecialty}}</b><em>Selon les catégories résolues</em></div></article></div><div class="xp-panel"><div class="xp-copy"><span><b>{{performance.experiencePoints}} XP</b> cumulés</span><span>Prochain niveau à {{performance.nextLevelExperience}} XP</span></div><div class="xp-track" [attr.aria-label]="performance.progressPercent+' % vers le niveau suivant'"><i [style.width.%]="performance.progressPercent"></i><span [style.left.%]="performance.progressPercent"></span></div><small>{{performance.progressPercent}} % du niveau {{performance.level}} complété</small></div><div class="badge-title"><div><span class="performance-eyebrow">DISTINCTIONS</span><h3>Collection de badges</h3></div><span>{{unlockedBadgeCount}} / {{performance.badges.length}} débloqués</span></div><div class="badge-gallery">@for(badge of performance.badges;track badge.code){<article [class.unlocked]="badge.unlocked" [class.locked]="!badge.unlocked"><div class="badge-medallion" [attr.data-tier]="badge.tier.toLowerCase()"><span>{{badge.icon}}</span>@if(badge.unlocked){<i>✓</i>}</div><div class="badge-copy"><div><h4>{{badge.name}}</h4><span>{{badge.tier}}</span></div><p>{{badge.description}}</p><div class="badge-progress"><i [style.width.%]="badgeProgress(badge.current,badge.target)"></i></div><small>{{badge.current}} / {{badge.target}} · {{badge.unlocked?'Débloqué':'En progression'}}</small></div></article>}</div></section>}
 <div class="profile-grid">
  <form #profileForm="ngForm" class="card form" (ngSubmit)="save()"><div><span class="section-icon">👤</span><h2>Informations personnelles</h2><p class="muted">Vos coordonnées et domaines d'expertise.</p></div><label>Prénom<input name="firstName" [(ngModel)]="firstName" required maxlength="80"></label><label>Nom<input name="lastName" [(ngModel)]="lastName" required maxlength="80"></label><label>E-mail<input name="email" [(ngModel)]="email" type="email" required email></label><label>Téléphone<input name="phoneNumber" [(ngModel)]="phoneNumber" maxlength="30" placeholder="+216 00 000 000"></label><label>Fonction<input name="jobTitle" [(ngModel)]="jobTitle" maxlength="120" placeholder="Technicien systèmes"></label><label>Compétences<textarea name="skills" [(ngModel)]="skillsText" rows="3" placeholder="Oracle, Réseau, TLS, .NET"></textarea><small>Séparez les compétences par une virgule (12 maximum).</small></label><div class="skill-list">@for(skill of parsedSkills;track skill){<span class="skill">{{skill}}</span>}</div><button class="primary" [disabled]="profileForm.invalid">Enregistrer le profil</button></form>
  <form #passwordForm="ngForm" class="card form" (ngSubmit)="changePassword()"><div><span class="section-icon">🔒</span><h2>Sécurité du compte</h2><p class="muted">Utilisez un mot de passe unique et difficile à deviner.</p></div><label>Mot de passe actuel<input name="current" [(ngModel)]="currentPassword" type="password" required autocomplete="current-password"></label><label>Nouveau mot de passe<input name="next" [(ngModel)]="newPassword" type="password" minlength="10" required autocomplete="new-password"></label><div class="strength"><span [style.width.%]="passwordScore*20" [class.strong]="passwordScore===5"></span></div><ul class="policy"><li [class.ok]="newPassword.length>=10">10 caractères minimum</li><li [class.ok]="hasUpper">Une lettre majuscule</li><li [class.ok]="hasLower">Une lettre minuscule</li><li [class.ok]="hasDigit">Un chiffre</li><li [class.ok]="hasSpecial">Un caractère spécial</li></ul><button class="primary" [disabled]="passwordForm.invalid||passwordScore<5">Modifier le mot de passe</button></form>
  <form #notificationForm="ngForm" class="card form notifications" (ngSubmit)="saveNotifications()"><div><span class="section-icon">🔔</span><h2>Notifications</h2><p class="muted">Choisissez les notifications internes et les e-mails SMTP Gmail. Le canal SMS est désactivé.</p></div><label class="choice"><input type="checkbox" name="inApp" [(ngModel)]="preferences.inAppEnabled"> Notifications internes</label><label class="choice"><input type="checkbox" name="emailEnabled" [(ngModel)]="preferences.emailEnabled"> E-mails STB Monitoring</label><label class="choice"><input type="checkbox" name="critical" [(ngModel)]="preferences.criticalOnly"> Uniquement les incidents critiques</label><button class="primary" [disabled]="notificationForm.invalid">Enregistrer les préférences</button></form>
 </div>
 @if(confirmAvatarDelete){<div class="modal-backdrop" (click)="confirmAvatarDelete=false"><section class="card avatar-delete-modal" (click)="$event.stopPropagation()"><div class="delete-orbit">⌫</div><span class="eyebrow danger-eyebrow">PHOTO DE PROFIL</span><h2>Supprimer cette photo ?</h2><p>Votre photo actuelle sera retirée et remplacée par l’avatar STB par défaut.</p><div class="modal-actions"><button type="button" (click)="confirmAvatarDelete=false">Conserver la photo</button><button class="danger-confirm" type="button" (click)="deleteAvatar()">⌫ Supprimer la photo</button></div></section></div>}
</section>`,styles:[`.profile-page{max-width:1180px}.profile-hero{display:flex;align-items:center;gap:24px;background:linear-gradient(125deg,#123b5d,#0b6574);color:white;border:0}.avatar-wrap{position:relative;flex:0 0 auto}.avatar{width:112px;height:112px;border-radius:50%;object-fit:cover;border:4px solid #ffffffcc;background:#e7f0f4}.avatar-action{position:absolute;right:0;bottom:2px;width:36px;height:36px;border-radius:50%;display:grid;place-items:center;background:#2cb5c0;border:3px solid white;cursor:pointer}.avatar-action input{display:none}.identity h1{margin:4px 0;font-size:2rem}.identity p{margin:0;color:#dceff2}.eyebrow{font-size:.75rem;letter-spacing:.15em;color:#7ee1e7}.profile-tags,.skill-list{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.achievement{background:#fff3cf;color:#815b00}.profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin-top:20px}.notifications{grid-column:1/-1}.form h2{display:inline;margin:0 0 0 8px}.muted,.upload-help,small{color:#61727e}.upload-help{margin:8px 4px 0;font-size:.86rem}.section-icon{font-size:1.2rem}.form textarea{padding:12px;border:1px solid #aabcc5;border-radius:8px;font:inherit;resize:vertical}.skill{padding:5px 10px;border-radius:7px;background:#eaf4f6;color:#087e8b;font-size:.85rem;font-weight:650}.choice{display:flex!important;align-items:center;gap:9px}.strength{height:7px;background:#e7ecef;border-radius:5px;overflow:hidden}.strength span{display:block;height:100%;background:#e89a19;transition:.25s}.strength span.strong{background:#198754}.policy{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:0;padding:0;list-style:none;color:#61727e;font-size:.86rem}.policy li:before{content:'○';margin-right:7px}.policy li.ok{color:#087443}.policy li.ok:before{content:'✓'}@media(max-width:760px){.profile-grid{grid-template-columns:1fr}.notifications{grid-column:auto}.profile-hero{align-items:flex-start}.avatar{width:88px;height:88px}.identity h1{font-size:1.45rem}.policy{grid-template-columns:1fr}}`]})
export class ProfileComponent{
 readonly api=API_ROOT;user:User|null=null;firstName='';lastName='';email='';phoneNumber='';jobTitle='';skillsText='';currentPassword='';newPassword='';message='';error='';avatarPreview='';confirmAvatarDelete=false;preferences={inAppEnabled:true,emailEnabled:true,smsEnabled:false,phoneNumber:'',criticalOnly:true};
 constructor(private http:HttpClient,private auth:AuthService){this.setUser(auth.currentUser());auth.me().subscribe({next:u=>this.setUser(u)});http.get<any>(`${this.api}/user-preferences/notifications`).subscribe(x=>this.preferences={...x,phoneNumber:x.phoneNumber||''})}
 get parsedSkills(){return this.skillsText.split(',').map(x=>x.trim()).filter(Boolean).slice(0,12)}get avatarSource(){return this.avatarPreview||(this.user?.avatarUrl?this.api.replace('/api','')+this.user.avatarUrl:'/default-avatar.svg')}get roleLabel(){return ({ADMIN:'Administrateur',MANAGER_IT:'Manager IT',SUPERVISOR:'Superviseur',TECHNICIAN:'Technicien'} as Record<string,string>)[this.user?.role||'']||'Utilisateur'}
 get hasUpper(){return /[A-Z]/.test(this.newPassword)}get hasLower(){return /[a-z]/.test(this.newPassword)}get hasDigit(){return /\d/.test(this.newPassword)}get hasSpecial(){return /[^A-Za-z0-9]/.test(this.newPassword)}get passwordScore(){return [this.newPassword.length>=10,this.hasUpper,this.hasLower,this.hasDigit,this.hasSpecial].filter(Boolean).length}
 get unlockedBadgeCount(){return this.user?.technicianPerformance?.badges.filter(x=>x.unlocked).length||0}badgeProgress(current:number,target:number){return Math.min(100,Math.round(100*current/Math.max(1,target)))}
 selectAvatar(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;this.reset();if(!['image/jpeg','image/png','image/webp'].includes(file.type)){this.error='Formats autorisés : JPG, PNG ou WebP.';return}if(file.size>2*1024*1024){this.error='La photo ne doit pas dépasser 2 Mo.';return}this.avatarPreview=URL.createObjectURL(file);const data=new FormData();data.append('file',file);this.http.post<User>(`${this.api}/auth/avatar`,data).subscribe({next:u=>{this.setUser(u);this.persist(u);this.message='Photo de profil mise à jour.'},error:e=>{this.avatarPreview='';this.error=e.error?.message||'Téléversement impossible.'}})}
 save(){this.reset();this.http.put<User>(`${this.api}/auth/profile`,{firstName:this.firstName,lastName:this.lastName,email:this.email,phoneNumber:this.phoneNumber,jobTitle:this.jobTitle,skills:this.parsedSkills}).subscribe({next:u=>{this.setUser(u);this.persist(u);this.message='Profil et compétences mis à jour.'},error:e=>this.error=e.error?.message||'Modification impossible.'})}deleteAvatar(){this.confirmAvatarDelete=false;this.reset();this.http.delete<User>(`${this.api}/auth/avatar`).subscribe({next:u=>{this.avatarPreview='';this.setUser(u);this.persist(u);this.message='Photo supprimée. L’image par défaut est utilisée.'},error:e=>this.error=e.error?.message||'Suppression impossible.'})}changePassword(){this.reset();this.http.post(`${this.api}/auth/change-password`,{currentPassword:this.currentPassword,newPassword:this.newPassword}).subscribe({next:()=>{this.currentPassword='';this.newPassword='';this.message='Mot de passe modifié.'},error:e=>this.error=e.error?.message||'Modification impossible.'})}saveNotifications(){this.reset();this.http.put(`${this.api}/user-preferences/notifications`,this.preferences).subscribe({next:()=>this.message='Préférences enregistrées.',error:e=>this.error=e.error?.message||'Enregistrement impossible.'})}
 private setUser(u:User|null){this.user=u;if(u){this.firstName=u.firstName;this.lastName=u.lastName;this.email=u.email;this.phoneNumber=u.phoneNumber||'';this.jobTitle=u.jobTitle||'';this.skillsText=(u.skills||[]).join(', ')}}private persist(u:User){localStorage.setItem('stb_user',JSON.stringify(u));this.auth.currentUser.set(u)}private reset(){this.message='';this.error=''}
}
