import {CommonModule} from '@angular/common';
import {Component,OnInit} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {OperationsService,SlaPolicy} from '../core/operations.service';

@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="page sla-page"><div class="page-title"><div><span class="eyebrow">SPRINT 3 · SLA</span><h1>Politiques de niveau de service</h1><p>Définissez les délais de prise en charge et de résolution par priorité.</p></div><button class="primary" (click)="create()">+ Nouvelle politique</button></div>
@if(error){<div class="error">{{error}}</div>}@if(message){<div class="success">{{message}}</div>}
<div class="sla-grid">@for(item of policies;track item.id){<article class="card" [class.inactive]="!item.isActive"><div class="card-head"><span [class]="'priority '+item.priority.toLowerCase()">{{item.priority}}</span><span [class]="item.isActive?'status active':'status inactive'">{{item.isActive?'Active':'Inactive'}}</span></div><h2>{{item.name}}</h2><p>{{item.description||'Aucune description'}}</p><div class="metrics"><div><b>{{duration(item.responseTimeMinutes)}}</b><small>Prise en charge</small></div><div><b>{{duration(item.resolutionTimeMinutes)}}</b><small>Résolution</small></div><div><b>{{item.warningPercentage}} %</b><small>Seuil d’alerte</small></div></div><div class="actions"><button (click)="edit(item)">Modifier</button><button (click)="toggle(item)">{{item.isActive?'Désactiver':'Activer'}}</button></div></article>}@empty{<div class="card empty">Aucune politique SLA configurée.</div>}</div>
@if(draft){<div class="modal-backdrop" (click)="draft=null"><form #form="ngForm" class="card modal form" (click)="$event.stopPropagation()" (ngSubmit)="save()"><div class="page-title"><div><span class="eyebrow">CONFIGURATION</span><h2>{{editing?'Modifier':'Créer'}} une politique</h2></div><button type="button" (click)="draft=null">×</button></div><label>Nom<input name="name" [(ngModel)]="draft.name" required minlength="3"></label><label>Description<textarea name="description" [(ngModel)]="draft.description"></textarea></label><label>Priorité<select name="priority" [(ngModel)]="draft.priority"><option>P1Critical</option><option>P2High</option><option>P3Medium</option><option>P4Low</option></select></label><div class="two"><label>Réponse (minutes)<input type="number" name="response" [(ngModel)]="draft.responseTimeMinutes" min="1" required></label><label>Résolution (minutes)<input type="number" name="resolution" [(ngModel)]="draft.resolutionTimeMinutes" min="1" required></label></div><label>Seuil d’avertissement (%)<input type="number" name="warning" [(ngModel)]="draft.warningPercentage" min="1" max="90" required></label><div class="actions end"><button type="button" (click)="draft=null">Annuler</button><button class="primary" [disabled]="form.invalid||saving">{{saving?'Enregistrement...':'Enregistrer'}}</button></div></form></div>}</section>`,styles:[`.sla-page{max-width:1200px}.sla-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px}.sla-grid .card{border-top:4px solid #0b8a80}.sla-grid .inactive{opacity:.65;border-top-color:#94a3b8}.card-head,.actions,.two{display:flex;gap:10px;justify-content:space-between}.priority,.status{padding:5px 9px;border-radius:20px;font-size:11px;font-weight:800}.priority.p1critical{background:#fee2e2;color:#b91c1c}.priority.p2high{background:#ffedd5;color:#c2410c}.priority.p3medium{background:#fef3c7;color:#a16207}.priority.p4low{background:#dbeafe;color:#1d4ed8}.status.active{background:#dcfce7;color:#15803d}.status.inactive{background:#e2e8f0;color:#475569}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:20px 0}.metrics div{background:#f4f7f9;border-radius:10px;padding:12px}.metrics b,.metrics small{display:block}.metrics small{color:#718294;margin-top:5px}.actions button{padding:8px 12px}.modal{width:min(590px,95vw)}.form{display:grid;gap:13px}.form label{display:grid;gap:6px}.form input,.form textarea,.form select{padding:10px;border:1px solid #cad7df;border-radius:8px}.two label{flex:1}.end{justify-content:flex-end}@media(max-width:550px){.two{display:grid}.metrics{grid-template-columns:1fr}}`]})
export class SlaComponent implements OnInit{policies:SlaPolicy[]=[];draft:any=null;editing:SlaPolicy|null=null;error='';message='';saving=false;constructor(private api:OperationsService){}ngOnInit(){this.load()}load(){this.api.slas().subscribe({next:x=>this.policies=x,error:e=>this.fail(e)})}create(){this.editing=null;this.draft={name:'',description:'',priority:'P3Medium',responseTimeMinutes:30,resolutionTimeMinutes:240,warningPercentage:75}}edit(x:SlaPolicy){this.editing=x;this.draft={...x}}save(){this.saving=true;this.api.saveSla(this.draft,this.editing?.id).subscribe({next:()=>{this.saving=false;this.draft=null;this.message='Politique SLA enregistrée.';this.load()},error:e=>{this.saving=false;this.fail(e)}})}toggle(x:SlaPolicy){this.api.slaActive(x.id,!x.isActive).subscribe({next:()=>this.load(),error:e=>this.fail(e)})}duration(minutes:number){return minutes<60?`${minutes} min`:minutes%60?`${Math.floor(minutes/60)} h ${minutes%60} min`:`${minutes/60} h`}fail(e:any){this.error=e.error?.message||`Erreur HTTP ${e.status||0}`}}
