import {Component,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute,RouterLink} from '@angular/router';
import {AuthService} from '../core/auth.service';
import {Endpoint,EndpointDraft,MonitoringService,SystemDetail} from '../core/monitoring.service';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`
<section class="page detail">@if(data){
 <a routerLink="/systems" class="back">← Retour aux systèmes</a>
 <div class="hero card"><div><span class="eyebrow">{{data.system.code}} · {{data.system.environment}}</span><h1>{{data.system.name}}</h1><p>{{data.system.description}}</p></div><div [class]="'big-status '+data.system.status.toLowerCase()"><i></i><b>{{data.system.status}}</b><small>{{data.system.lastCheckedAt?(data.system.lastCheckedAt|date:'dd/MM/yyyy HH:mm:ss'):'Jamais contrôlé'}}</small></div></div>
 @if(message){<div class="success">{{message}}</div>} @if(error){<div class="error">{{error}}</div>}
 <div class="section-title"><div><span class="eyebrow">POINTS DE CONTRÔLE</span><h2>Endpoints surveillés</h2></div><button class="primary" *ngIf="auth.hasPermission('systems.manage')" (click)="newEndpoint()">+ Ajouter</button></div>
 <div class="endpoints">@for(e of data.endpoints;track e.id){<article class="card endpoint"><div class="endpoint-title"><span [class]="'dot '+e.status.toLowerCase()"></span><div><h3>{{e.name}}</h3><small>{{e.checkType}} · toutes les {{e.intervalSeconds}} s</small></div><span [class]="'badge '+e.status.toLowerCase()">{{e.status}}</span></div><code>{{e.httpMethod}} {{e.url}}</code><div class="info"><span>Attendu <b>{{e.expectedStatusCode}}</b></span><span>Latence <b>{{e.lastDurationMs??'-'}} ms</b></span><span>Critique <b>{{e.isCritical?'Oui':'Non'}}</b></span></div>@if(e.lastError){<p class="endpoint-error">{{e.lastError}}</p>}<div class="actions"><button (click)="execute(e)" [disabled]="running===e.id" *ngIf="auth.hasPermission('checks.execute')">{{running===e.id?'Contrôle...':'Tester maintenant'}}</button><button (click)="editEndpoint(e)" *ngIf="auth.hasPermission('systems.manage')">Modifier</button><button (click)="active(e)" *ngIf="auth.hasPermission('systems.manage')">{{e.isActive?'Désactiver':'Activer'}}</button><button class="danger" (click)="remove(e)" *ngIf="auth.hasPermission('systems.manage')">Supprimer</button></div></article>}</div>
 <section class="card history"><div class="section-title"><div><span class="eyebrow">HISTORIQUE</span><h2>Derniers contrôles</h2></div><span>{{data.recentResults.length}} résultats</span></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Endpoint</th><th>État</th><th>Durée</th><th>HTTP</th><th>Origine</th><th>Erreur</th></tr></thead><tbody>@for(r of data.recentResults;track r.id){<tr><td>{{r.startedAt|date:'dd/MM HH:mm:ss'}}</td><td>{{r.endpointName}}</td><td><span [class]="'badge '+r.status.toLowerCase()">{{r.status}}</span></td><td>{{r.durationMs}} ms</td><td>{{r.httpStatusCode??'-'}}</td><td>{{r.triggeredManually?'Manuel':'Worker'}}</td><td>{{r.errorMessage||'-'}}</td></tr>}</tbody></table></div></section>}
 @if(draft){<div class="modal-backdrop" (click)="draft=null"><form #f="ngForm" class="card modal endpoint-form" (click)="$event.stopPropagation()" (ngSubmit)="saveEndpoint()"><div class="page-title"><h2>{{editing?'Modifier':'Ajouter'}} un contrôle</h2><button type="button" (click)="draft=null">×</button></div><label>Nom<input name="name" [(ngModel)]="draft.name" required></label><label class="wide">URL<input name="url" [(ngModel)]="draft.url" required type="url"></label><label>Type<select name="type" [(ngModel)]="draft.checkType"><option>Http</option><option>ApiJson</option><option>Tls</option></select></label><label>Méthode<select name="method" [(ngModel)]="draft.httpMethod"><option>GET</option><option>HEAD</option><option>POST</option></select></label><label>HTTP attendu<input name="status" [(ngModel)]="draft.expectedStatusCode" type="number" min="100" max="599"></label><label>Timeout (s)<input name="timeout" [(ngModel)]="draft.timeoutSeconds" type="number" min="1" max="300"></label><label>Intervalle (s)<input name="interval" [(ngModel)]="draft.intervalSeconds" type="number" min="10"></label><label>Seuil dégradé (ms)<input name="degraded" [(ngModel)]="draft.degradedThresholdMs" type="number" min="1"></label><label>Seuil KO (ms)<input name="down" [(ngModel)]="draft.downThresholdMs" type="number" min="1"></label><label class="inline"><input name="critical" [(ngModel)]="draft.isCritical" type="checkbox"> Critique</label>@if(draft.checkType==='ApiJson'){<label>Propriété JSON<input name="property" [(ngModel)]="draft.expectedJsonProperty"></label><label>Valeur attendue<input name="value" [(ngModel)]="draft.expectedJsonValue"></label>}<button class="primary wide" [disabled]="f.invalid">Enregistrer</button></form></div>}
</section>`,styles:[`.detail{max-width:1280px}.back{display:inline-block;margin-bottom:16px;color:#087e76;text-decoration:none;font-weight:700}.hero{display:flex;justify-content:space-between;align-items:center;background:linear-gradient(135deg,#fff,#eef9f8);margin-bottom:22px}.hero h1{margin:5px 0;font-size:30px}.hero p{color:#718294}.eyebrow{font-size:10px;font-weight:800;letter-spacing:.14em;color:#078578}.big-status{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:8px}.big-status i,.dot{width:12px;height:12px;border-radius:50%;background:#94a3b8}.big-status b{font-size:21px}.big-status small{grid-column:1/-1;color:#718294}.big-status.up i,.dot.up{background:#10b981}.big-status.degraded i,.dot.degraded{background:#f59e0b}.big-status.down i,.dot.down{background:#ef4444}.section-title{display:flex;justify-content:space-between;align-items:center;margin:20px 0 13px}.section-title h2{margin:3px 0}.endpoints{display:grid;grid-template-columns:repeat(auto-fit,minmax(390px,1fr));gap:15px}.endpoint-title{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px}.endpoint-title h3{margin:0}.endpoint-title small{color:#718294}.endpoint code{display:block;background:#0e2033;color:#93e5d7;padding:12px;border-radius:9px;margin:14px 0;overflow:auto}.info{display:grid;grid-template-columns:repeat(3,1fr)}.info span{display:grid;font-size:11px;color:#718294}.endpoint-error{color:#b42318;background:#feeceb;padding:8px;border-radius:7px}.actions{margin-top:14px;flex-wrap:wrap}.actions button{padding:8px 10px;border:1px solid #d4e0e7;background:white;border-radius:8px}.actions .danger{color:#b42318}.history{margin-top:22px}.history .section-title{margin-top:0}.badge.up{background:#e5f7ef;color:#087443}.badge.degraded{background:#fff3d9;color:#9a5b00}.badge.down{background:#feeceb;color:#b42318}.endpoint-form{display:grid;grid-template-columns:1fr 1fr;gap:14px;width:min(760px,100%);max-height:92vh;overflow:auto}.endpoint-form .page-title,.endpoint-form .wide{grid-column:1/-1}.inline{display:flex;align-items:center;gap:8px}@media(max-width:650px){.hero{align-items:start;flex-direction:column;gap:18px}.endpoints{grid-template-columns:1fr}.endpoint-form{grid-template-columns:1fr}.endpoint-form .wide{grid-column:auto}}`]})
export class SystemDetailComponent implements OnInit{
 data?:SystemDetail;draft:EndpointDraft|null=null;editing:Endpoint|null=null;running='';message='';error='';id='';
 constructor(public auth:AuthService,private api:MonitoringService,route:ActivatedRoute){this.id=route.snapshot.paramMap.get('id')!} ngOnInit(){this.load()}
 load(){this.api.detail(this.id).subscribe({next:x=>this.data=x,error:e=>this.fail(e)})}
 newEndpoint(){this.editing=null;this.draft={name:'',url:'',checkType:'Http',httpMethod:'GET',expectedStatusCode:200,timeoutSeconds:10,intervalSeconds:60,degradedThresholdMs:1000,downThresholdMs:5000,isCritical:true,expectedJsonProperty:'',expectedJsonValue:''}}
 editEndpoint(e:Endpoint){this.editing=e;this.draft={name:e.name,url:e.url,checkType:e.checkType,httpMethod:e.httpMethod,expectedStatusCode:e.expectedStatusCode,timeoutSeconds:e.timeoutSeconds,intervalSeconds:e.intervalSeconds,degradedThresholdMs:e.degradedThresholdMs,downThresholdMs:e.downThresholdMs,isCritical:e.isCritical,expectedJsonProperty:e.expectedJsonProperty||'',expectedJsonValue:e.expectedJsonValue||''}}
 saveEndpoint(){if(!this.draft)return;this.request(this.editing?this.api.updateEndpoint(this.editing.id,this.draft):this.api.createEndpoint(this.id,this.draft),'Contrôle enregistré.',()=>this.draft=null)}
 execute(e:Endpoint){this.running=e.id;this.request(this.api.execute(e.id),'Contrôle exécuté.',()=>this.running='')}
 active(e:Endpoint){this.request(this.api.endpointActive(e.id,!e.isActive),`Contrôle ${e.isActive?'désactivé':'activé'}.`)}
 remove(e:Endpoint){if(confirm(`Supprimer le contrôle ${e.name} ?`))this.request(this.api.deleteEndpoint(e.id),'Contrôle supprimé.')}
 request(call:any,msg:string,after?:()=>void){this.error='';call.subscribe({next:()=>{after?.();this.message=msg;this.load()},error:(e:any)=>{this.running='';this.fail(e)}})}
 fail(e:any){this.error=e.error?.message||Object.values(e.error?.errors||{}).flat().join(' ')||`Erreur HTTP ${e.status}`}
}
