/** Administration des comptes, rôles fixes et activation/désactivation. */
import {Component,OnInit} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {HttpClient} from '@angular/common/http';
import {AuthService,User} from '../core/auth.service';
import {CommonModule} from '@angular/common';

@Component({standalone:true,imports:[FormsModule,CommonModule],template:`
<section class="page">
  <div class="page-title"><div><h1>Gestion des utilisateurs</h1><p>Créer, rechercher, modifier et activer les comptes.</p></div><button class="primary" (click)="showCreate=!showCreate" *ngIf="auth.hasPermission('users.manage')">{{showCreate?'Fermer':'Nouvel utilisateur'}}</button></div>
  @if(message){<div class="success">{{message}}</div>} @if(error){<div class="error">{{error}}</div>}
  @if(showCreate){<form #createForm="ngForm" class="card form form-grid" (ngSubmit)="create()"><h2>Inviter un utilisateur</h2><p class="muted">L’utilisateur recevra un lien sécurisé pour définir lui-même son mot de passe. Aucun mot de passe ne sera envoyé par e-mail.</p><label>Username<input #username="ngModel" name="username" [(ngModel)]="draft.username" required minlength="3">@if(username.touched&&username.invalid){<small class="field-error">3 caractères minimum.</small>}</label><label>Prénom<input #firstName="ngModel" name="firstName" [(ngModel)]="draft.firstName" required>@if(firstName.touched&&firstName.invalid){<small class="field-error">Prénom obligatoire.</small>}</label><label>Nom<input #lastName="ngModel" name="lastName" [(ngModel)]="draft.lastName" required>@if(lastName.touched&&lastName.invalid){<small class="field-error">Nom obligatoire.</small>}</label><label>E-mail<input #email="ngModel" name="email" type="email" [(ngModel)]="draft.email" required email>@if(email.touched&&email.invalid){<small class="field-error">Adresse e-mail valide obligatoire.</small>}</label><label>Rôle<select name="role" [(ngModel)]="draft.role" required>@for(role of roles;track role){<option [value]="role">{{role}}</option>}</select></label><button class="primary" [disabled]="createForm.invalid">Créer et envoyer l’invitation</button></form>}
  <input class="search" placeholder="Rechercher par nom, username, e-mail, rôle ou statut" [(ngModel)]="query">
  <div class="card table-wrap"><table><thead><tr><th>Utilisateur</th><th>E-mail</th><th>Rôle</th><th>État</th><th>Actions</th></tr></thead><tbody>
  @for(user of filtered;track user.id){<tr><td><div class="user-cell"><img [src]="avatar(user)" alt=""><span><strong>{{user.firstName}} {{user.lastName}}</strong><small>&#64;{{user.username}} · {{user.badge||'Membre'}}</small></span></div></td><td>{{user.email}}</td><td><span class="badge">{{user.role}}</span></td><td><span [class]="user.isActive?'status active':'status inactive'">{{user.isActive?'Actif':'Inactif'}}</span></td><td class="actions">@if(auth.hasPermission('users.manage')){<button (click)="edit(user)">Modifier</button><button (click)="active(user)">{{user.isActive?'Désactiver':'Activer'}}</button>@if(eligibility[user.id]?.canDelete){<button class="danger-action" (click)="deleteTarget=user">Supprimer définitivement</button>}}</td></tr>}
  </tbody></table></div>
  @if(selected){<div class="modal-backdrop" (click)="selected=null"><form #editForm="ngForm" class="card modal form" (click)="$event.stopPropagation()" (ngSubmit)="save()"><div class="page-title"><h2>Modifier {{selected.username}}</h2><button type="button" (click)="selected=null">×</button></div><label>Prénom<input name="editFirstName" [(ngModel)]="editDraft.firstName" required></label><label>Nom<input name="editLastName" [(ngModel)]="editDraft.lastName" required></label><label>E-mail<input name="editEmail" type="email" [(ngModel)]="editDraft.email" required email></label><label>Rôle<select name="editRole" [(ngModel)]="editDraft.role" required>@for(role of roles;track role){<option [value]="role">{{role}}</option>}</select></label>@if(editForm.touched&&editForm.invalid){<small class="field-error">Tous les champs doivent être valides.</small>}<button class="primary" [disabled]="editForm.invalid">Enregistrer</button></form></div>}
  @if(deleteTarget){<div class="modal-backdrop" (click)="deleteTarget=null"><section class="card modal delete-modal" (click)="$event.stopPropagation()"><div class="danger-icon">!</div><h2>Supprimer définitivement ?</h2><p>Le compte <strong>{{deleteTarget.firstName}} {{deleteTarget.lastName}}</strong> (&#64;{{deleteTarget.username}}) sera supprimé sans possibilité de restauration.</p><div class="warning-box">Cette action est autorisée uniquement parce que ce compte ne possède aucune activité.</div><div class="modal-actions"><button (click)="deleteTarget=null">Annuler</button><button class="danger-action" (click)="removePermanently()">Supprimer définitivement</button></div></section></div>}
</section>`,styles:[`.user-cell{display:flex;align-items:center;gap:11px}.user-cell img{width:42px;height:42px;object-fit:cover;border-radius:12px;background:#eaf4f6;border:1px solid #d7e5e9}.user-cell span{display:grid}.user-cell small{margin-top:3px;color:#61727e}.danger-action{color:#fff!important;background:#b42318!important;border-color:#b42318!important}.danger-action:hover{background:#8f1c13!important;transform:translateY(-1px)}.delete-modal{text-align:center;max-width:500px}.danger-icon{display:grid;place-items:center;width:52px;height:52px;margin:0 auto 12px;border-radius:16px;background:#fee4e2;color:#b42318;font-size:28px;font-weight:800}.warning-box{margin:16px 0;padding:12px;border:1px solid #fecdca;border-radius:10px;background:#fff6f5;color:#912018;text-align:left}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}`]})
export class UsersComponent implements OnInit{
 users:User[]=[];readonly roles=['ADMIN','SUPERVISOR','TECHNICIAN','MANAGER_IT'];query='';showCreate=false;selected:User|null=null;deleteTarget:User|null=null;eligibility:Partial<Record<string,{canDelete:boolean;reason:string}>>={};message='';error='';readonly base='http://localhost:5041/api';
 draft={username:'',firstName:'',lastName:'',email:'',role:'TECHNICIAN'};editDraft={firstName:'',lastName:'',email:'',role:''};
 constructor(private http:HttpClient,public auth:AuthService){}
 get filtered(){const q=this.query.trim().toLowerCase();return this.users.filter(u=>!q||[u.firstName,u.lastName,u.username,u.email,u.role,u.isActive?'actif':'inactif'].some(v=>v.toLowerCase().includes(q)))}
 ngOnInit(){this.load()}
 load(){this.http.get<User[]>(`${this.base}/users`).subscribe({next:x=>{this.users=x;this.loadEligibility()},error:e=>this.fail(e)})}
 loadEligibility(){this.eligibility={};if(!this.auth.hasPermission('users.manage'))return;for(const user of this.users)this.http.get<{canDelete:boolean;reason:string}>(`${this.base}/users/${user.id}/deletion-eligibility`).subscribe({next:x=>this.eligibility[user.id]=x})}
 create(){this.clear();this.http.post(`${this.base}/users`,this.draft).subscribe({next:()=>{this.draft={username:'',firstName:'',lastName:'',email:'',role:'TECHNICIAN'};this.showCreate=false;this.message='Utilisateur créé et invitation envoyée.';this.load()},error:e=>this.fail(e)})}
 edit(u:User){this.selected=u;this.editDraft={firstName:u.firstName,lastName:u.lastName,email:u.email,role:u.role}}
 save(){if(!this.selected)return;this.clear();this.http.put<User>(`${this.base}/users/${this.selected.id}`,this.editDraft).subscribe({next:()=>{this.selected=null;this.message='Utilisateur modifié.';this.load()},error:e=>this.fail(e)})}
 active(u:User){this.clear();this.http.patch(`${this.base}/users/${u.id}/active?value=${!u.isActive}`,{}).subscribe({next:()=>{u.isActive=!u.isActive;this.message=`Compte ${u.isActive?'activé':'désactivé'}.`},error:e=>this.fail(e)})}
 removePermanently(){if(!this.deleteTarget)return;const username=this.deleteTarget.username;this.clear();this.http.delete(`${this.base}/users/${this.deleteTarget.id}`).subscribe({next:()=>{this.deleteTarget=null;this.message=`Le compte ${username} a été supprimé définitivement.`;this.load()},error:e=>{this.deleteTarget=null;this.fail(e)}})}
 avatar(u:User){return u.avatarUrl?`http://localhost:5041${u.avatarUrl}`:'/default-avatar.svg'}
 clear(){this.message='';this.error=''} fail(e:any){this.error=e.error?.message||'Opération impossible.'}
}
