using System.Diagnostics;using System.Net.Security;using System.Net.Sockets;using System.Text.Json;using StbMonitoring.Application.Contracts;using StbMonitoring.Application.Interfaces;using StbMonitoring.Domain.Entities;
namespace StbMonitoring.Infrastructure.Monitoring;
public sealed class HttpCheckExecutor:ICheckExecutor{public CheckType Type=>CheckType.Http;public Task<CheckExecution>ExecuteAsync(MonitoringEndpoint e,CancellationToken ct)=>HttpRunner.RunAsync(e,false,ct);}
public sealed class ApiJsonCheckExecutor:ICheckExecutor{public CheckType Type=>CheckType.ApiJson;public Task<CheckExecution>ExecuteAsync(MonitoringEndpoint e,CancellationToken ct)=>HttpRunner.RunAsync(e,true,ct);}
internal static class HttpRunner
{
 public static async Task<CheckExecution>RunAsync(MonitoringEndpoint e,bool validateJson,CancellationToken ct){var started=DateTime.UtcNow;var sw=Stopwatch.StartNew();using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct);timeout.CancelAfter(TimeSpan.FromSeconds(e.TimeoutSeconds));try{using var client=new HttpClient();using var request=new HttpRequestMessage(new HttpMethod(e.HttpMethod),e.Url);using var response=await client.SendAsync(request,HttpCompletionOption.ResponseContentRead,timeout.Token);var body=await response.Content.ReadAsStringAsync(timeout.Token);sw.Stop();var error=(int)response.StatusCode==e.ExpectedStatusCode?null:$"Code HTTP {(int)response.StatusCode}, attendu {e.ExpectedStatusCode}.";if(error is null&&validateJson&&!string.IsNullOrWhiteSpace(e.ExpectedJsonProperty)){using var json=JsonDocument.Parse(body);JsonElement current=json.RootElement;foreach(var part in e.ExpectedJsonProperty.Split('.'))if(!current.TryGetProperty(part,out current)){error=$"Propriété JSON {e.ExpectedJsonProperty} absente.";break;}if(error is null&&e.ExpectedJsonValue is not null&&!JsonValueMatches(current,e.ExpectedJsonValue))error=$"Valeur JSON attendue {e.ExpectedJsonValue}, reçue {current}.";}var status=Calculate(e,sw.ElapsedMilliseconds,error);return new(e.Id,status,error is null,started,DateTime.UtcNow,sw.ElapsedMilliseconds,(int)response.StatusCode,error is null?null:"VALIDATION",error,validateJson?"API_JSON":"HTTP");}catch(OperationCanceledException)when(!ct.IsCancellationRequested){sw.Stop();return new(e.Id,MonitoringStatus.Down,false,started,DateTime.UtcNow,sw.ElapsedMilliseconds,null,"TIMEOUT","Délai d'attente dépassé.",null);}catch(Exception ex){sw.Stop();return new(e.Id,MonitoringStatus.Down,false,started,DateTime.UtcNow,sw.ElapsedMilliseconds,null,"NETWORK",ex.Message,null);}}
 private static bool JsonValueMatches(JsonElement value,string expected)=>value.ValueKind switch{JsonValueKind.True=>bool.TryParse(expected,out var parsed)&&parsed,JsonValueKind.False=>bool.TryParse(expected,out var parsed)&&!parsed,JsonValueKind.String=>string.Equals(value.GetString(),expected,StringComparison.OrdinalIgnoreCase),_=>string.Equals(value.ToString(),expected,StringComparison.OrdinalIgnoreCase)};
 private static MonitoringStatus Calculate(MonitoringEndpoint e,long ms,string? error)=>error is not null||ms>=e.DownThresholdMs?MonitoringStatus.Down:ms>=e.DegradedThresholdMs?MonitoringStatus.Degraded:MonitoringStatus.Up;
}
public sealed class TlsCheckExecutor:ICheckExecutor
{
 public CheckType Type=>CheckType.Tls;
 public async Task<CheckExecution>ExecuteAsync(MonitoringEndpoint e,CancellationToken ct){var started=DateTime.UtcNow;var sw=Stopwatch.StartNew();try{var uri=new Uri(e.Url);using var tcp=new TcpClient();using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct);timeout.CancelAfter(TimeSpan.FromSeconds(e.TimeoutSeconds));await tcp.ConnectAsync(uri.Host,uri.Port>0?uri.Port:443,timeout.Token);using var ssl=new SslStream(tcp.GetStream(),false);await ssl.AuthenticateAsClientAsync(uri.Host);var cert=ssl.RemoteCertificate??throw new InvalidOperationException("Certificat TLS absent.");var expiry=DateTime.Parse(cert.GetExpirationDateString()).ToUniversalTime();var days=(int)Math.Floor((expiry-DateTime.UtcNow).TotalDays);sw.Stop();var status=days<=7?MonitoringStatus.Down:days<=30?MonitoringStatus.Degraded:MonitoringStatus.Up;return new(e.Id,status,status!=MonitoringStatus.Down,started,DateTime.UtcNow,sw.ElapsedMilliseconds,null,status==MonitoringStatus.Down?"TLS_EXPIRY":null,status==MonitoringStatus.Down?$"Certificat expiré ou expire dans {days} jours.":null,JsonSerializer.Serialize(new{subject=cert.Subject,issuer=cert.Issuer,expiresAt=expiry,daysRemaining=days}));}catch(Exception ex){sw.Stop();return new(e.Id,MonitoringStatus.Down,false,started,DateTime.UtcNow,sw.ElapsedMilliseconds,null,"TLS",ex.Message,null);}}
}
