apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stb-prod
resources: [../../base, namespace.yaml]
images:
  - name: registry.local/stb-monitoring/api
    newName: host.docker.internal:8082/stb-monitoring-api
    newTag: bootstrap
  - name: registry.local/stb-monitoring/frontend
    newName: host.docker.internal:8082/stb-monitoring-frontend
    newTag: bootstrap
  - name: registry.local/stb-monitoring/ai-service
    newName: host.docker.internal:8082/stb-monitoring-ai
    newTag: bootstrap
patches:
  - target: { kind: Deployment, name: stb-api }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target: { kind: Deployment, name: stb-frontend }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
