apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stb-demo-prod
resources: [../../base, namespace.yaml]
patches:
  - target: { kind: Deployment, name: stb-api }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target: { kind: Deployment, name: stb-frontend }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
